/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DoctorsPortal;

import Login.DoctorLogin;
import PatientsInfo.Home;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author kli ann
 */
public class DoctorsModule extends javax.swing.JFrame {

    /**
     * Creates new form DoctorsPortal2
     */
    public DoctorsModule() {
        initComponents();
        ImageIcon ic = new ImageIcon(getClass().getResource("background.jpg")); 
        Image img = ic.getImage().getScaledInstance(1350, 1600, Image.SCALE_SMOOTH);
        labelBackground.setIcon(new ImageIcon(img) );
        
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        DoctorsProfile = new javax.swing.JButton();
        btnAppointments = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        labelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Doctor's Module");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 60, 260, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PatientsInfo/portal.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 50, 302, 85);

        btnLogout.setBackground(new java.awt.Color(0, 153, 153));
        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout);
        btnLogout.setBounds(110, 420, 110, 40);

        DoctorsProfile.setBackground(new java.awt.Color(255, 255, 255));
        DoctorsProfile.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        DoctorsProfile.setForeground(new java.awt.Color(0, 153, 153));
        DoctorsProfile.setText("Edit Profile");
        DoctorsProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DoctorsProfileMouseClicked(evt);
            }
        });
        DoctorsProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorsProfileActionPerformed(evt);
            }
        });
        jPanel1.add(DoctorsProfile);
        DoctorsProfile.setBounds(50, 200, 230, 60);

        btnAppointments.setBackground(new java.awt.Color(255, 255, 255));
        btnAppointments.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAppointments.setForeground(new java.awt.Color(0, 153, 153));
        btnAppointments.setText("Appointments");
        btnAppointments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAppointmentsMouseClicked(evt);
            }
        });
        jPanel1.add(btnAppointments);
        btnAppointments.setBounds(50, 310, 230, 60);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(50, 200, 230, 60);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(50, 310, 230, 60);

        labelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PatientsInfo/background.jpg"))); // NOI18N
        labelBackground.setText("  ");
        jPanel1.add(labelBackground);
        labelBackground.setBounds(0, 0, 1650, 1450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1638, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1729, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int lg = JOptionPane.showConfirmDialog(null, "Are you sure you want to Log out?","Doctors's Portal", JOptionPane.YES_NO_OPTION);
        if (lg==0){
            Home h = new Home();
            h.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void DoctorsProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorsProfileActionPerformed
        // TODO add your handling code here:
        Doctor_Profile dp = new Doctor_Profile();
        dp.setVisible(true);
        dispose();
    }//GEN-LAST:event_DoctorsProfileActionPerformed

    private void DoctorsProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoctorsProfileMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorsProfileMouseClicked

    private void btnAppointmentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAppointmentsMouseClicked
        // TODO add your handling code here:
        AllAppointments ap = new AllAppointments();
        ap.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAppointmentsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorsModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorsModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorsModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorsModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorsModule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DoctorsProfile;
    private javax.swing.JButton btnAppointments;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelBackground;
    // End of variables declaration//GEN-END:variables
}
