/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DoctorsPortal;

import Doctor.Doctors2;
import Nurse.Nurse;
import java.awt.Frame;
import java.awt.HeadlessException;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author kli ann
 */
public class Doctor_Profile extends javax.swing.JFrame {

    /**
     * Creates new form Doctor_Profile
     */
    public Doctor_Profile() {
        initComponents();
        ImageIcon ad = new ImageIcon(getClass().getResource("doctor.png")); 
        Image image = ad.getImage().getScaledInstance(110, 130, Image.SCALE_SMOOTH);
        Logo.setIcon(new ImageIcon(image) );
        
        ImageIcon home = new ImageIcon(getClass().getResource("home.jpg")); 
        Image img = home.getImage().getScaledInstance(52, 57, Image.SCALE_SMOOTH);
        jLabelHome1.setIcon(new ImageIcon(img) );
        
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    String ImgPath = null;
    
    public ImageIcon ResizeImage(String imagePath, byte[] pix){
        ImageIcon myImage = null;
        
        if(imagePath != null){
            myImage = new ImageIcon(imagePath);
        }else{
            myImage = new ImageIcon(pix);
        }
        Image img = myImage.getImage();
        Image img2 = img.getScaledInstance(lbl_image1.getWidth(), lbl_image1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img2);
        return image;
    }
    
    //Connection to database
    public Connection getConnection() {
        Connection con = null;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/Hospital", "root", "");
            return con;
        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, "Not connected" + ex);
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabelHome1 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtLname = new javax.swing.JTextField();
        txtBdate = new javax.swing.JTextField();
        txtSearch1 = new javax.swing.JTextField();
        jLabel73 = new javax.swing.JLabel();
        txtContract = new javax.swing.JTextField();
        jLabel74 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        rdoMale = new javax.swing.JRadioButton();
        rdoFemale = new javax.swing.JRadioButton();
        cmboStatus = new javax.swing.JComboBox();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel24 = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        jPanel25 = new javax.swing.JPanel();
        lbl_image = new javax.swing.JLabel();
        lbl_image1 = new javax.swing.JLabel();
        btnSearch1 = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        jLabel76 = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        jLabel77 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        txtDate = new javax.swing.JTextField();
        jLabel78 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jLabel79 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel80 = new javax.swing.JLabel();
        btn_Image = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel22.setBackground(new java.awt.Color(204, 255, 255));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel23.setBackground(new java.awt.Color(0, 204, 204));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Edit Profile");
        jPanel23.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jLabelHome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Receptionist/home.jpg"))); // NOI18N
        jLabelHome1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelHome1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHome1MouseClicked(evt);
            }
        });
        jPanel23.add(jLabelHome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, 90, 60));

        jLabel66.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setText("Home");
        jPanel23.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 70, -1, -1));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doctor/doctor.png"))); // NOI18N
        jPanel23.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 120, 90));

        jPanel22.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 90));

        jLabel67.setBackground(new java.awt.Color(204, 204, 255));
        jLabel67.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(0, 153, 153));
        jLabel67.setText("Address:");
        jPanel22.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 590, -1, -1));

        jLabel68.setBackground(new java.awt.Color(204, 204, 255));
        jLabel68.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(0, 153, 153));
        jLabel68.setText("Doctor ID:");
        jPanel22.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, -1, -1));

        jLabel69.setBackground(new java.awt.Color(204, 204, 255));
        jLabel69.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(0, 153, 153));
        jLabel69.setText("Last Name:");
        jPanel22.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, -1, -1));

        jLabel70.setBackground(new java.awt.Color(204, 204, 255));
        jLabel70.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(0, 153, 153));
        jLabel70.setText("Sex:");
        jPanel22.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, -1, -1));

        jLabel71.setBackground(new java.awt.Color(204, 204, 255));
        jLabel71.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(0, 153, 153));
        jLabel71.setText("B-date:");
        jPanel22.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, -1, -1));

        jLabel72.setBackground(new java.awt.Color(204, 204, 255));
        jLabel72.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(0, 153, 153));
        jLabel72.setText("Marital Status:");
        jPanel22.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 530, -1, 20));

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        jPanel22.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 580, 690, 40));

        txtLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLnameActionPerformed(evt);
            }
        });
        jPanel22.add(txtLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 270, 240, 40));
        jPanel22.add(txtBdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 240, 40));

        txtSearch1.setText("Type your ID here...");
        txtSearch1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearch1MouseClicked(evt);
            }
        });
        txtSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearch1ActionPerformed(evt);
            }
        });
        jPanel22.add(txtSearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 200, 30));

        jLabel73.setBackground(new java.awt.Color(204, 204, 255));
        jLabel73.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(0, 153, 153));
        jLabel73.setText("Phone:");
        jPanel22.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, -1, -1));
        jPanel22.add(txtContract, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 430, 240, 30));

        jLabel74.setBackground(new java.awt.Color(204, 204, 255));
        jLabel74.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(0, 153, 153));
        jLabel74.setText("Contract No.:");
        jPanel22.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, -1, -1));
        jPanel22.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, 240, 30));

        rdoMale.setBackground(new java.awt.Color(51, 255, 153));
        buttonGroup1.add(rdoMale);
        rdoMale.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdoMale.setForeground(new java.awt.Color(0, 102, 102));
        rdoMale.setText("Male");
        rdoMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoMaleActionPerformed(evt);
            }
        });
        jPanel22.add(rdoMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, -1, -1));

        rdoFemale.setBackground(new java.awt.Color(51, 255, 153));
        buttonGroup1.add(rdoFemale);
        rdoFemale.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdoFemale.setForeground(new java.awt.Color(0, 102, 102));
        rdoFemale.setText("Female");
        jPanel22.add(rdoFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, -1, -1));

        cmboStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmboStatus.setForeground(new java.awt.Color(0, 153, 153));
        cmboStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Single", "Married", "Divorced", "Widow" }));
        cmboStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmboStatusActionPerformed(evt);
            }
        });
        jPanel22.add(cmboStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 530, 240, 30));
        jPanel22.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 1450, 10));

        jPanel24.setBackground(new java.awt.Color(51, 255, 153));

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel22.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 240, 40));

        btnUpdate.setBackground(new java.awt.Color(0, 153, 153));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel22.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 520, 120, 30));

        jPanel25.setBackground(new java.awt.Color(255, 255, 255));
        jPanel25.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), new java.awt.Color(0, 204, 204)));

        lbl_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DoctorsPortal/doctor.png"))); // NOI18N

        lbl_image1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DoctorsPortal/doctor.png"))); // NOI18N

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_image, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel25Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbl_image1, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_image, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel25Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbl_image1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel22.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 210, 180, 180));

        btnSearch1.setBackground(new java.awt.Color(0, 153, 153));
        btnSearch1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearch1.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch1.setText("Search");
        btnSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch1ActionPerformed(evt);
            }
        });
        jPanel22.add(btnSearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, 110, 30));
        jPanel22.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 380, 240, 30));

        jLabel76.setBackground(new java.awt.Color(204, 204, 255));
        jLabel76.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(0, 153, 153));
        jLabel76.setText("Email:");
        jPanel22.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, -1, -1));

        txtFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFnameActionPerformed(evt);
            }
        });
        jPanel22.add(txtFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 240, 40));

        jLabel77.setBackground(new java.awt.Color(204, 204, 255));
        jLabel77.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(0, 153, 153));
        jLabel77.setText("First Name:");
        jPanel22.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        btnClear.setBackground(new java.awt.Color(0, 153, 153));
        btnClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel22.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 520, 110, 30));
        jPanel22.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 480, 240, 30));

        jLabel78.setBackground(new java.awt.Color(204, 204, 255));
        jLabel78.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(0, 153, 153));
        jLabel78.setText("DateEmployed:");
        jPanel22.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 480, -1, 20));

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        jPanel22.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, 240, 40));

        jLabel79.setBackground(new java.awt.Color(204, 204, 255));
        jLabel79.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(0, 153, 153));
        jLabel79.setText("Password:");
        jPanel22.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 530, -1, -1));
        jPanel22.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 240, 40));

        jLabel80.setBackground(new java.awt.Color(204, 204, 255));
        jLabel80.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(0, 153, 153));
        jLabel80.setText("Username:");
        jPanel22.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, -1, -1));

        btn_Image.setBackground(new java.awt.Color(0, 153, 153));
        btn_Image.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Image.setForeground(new java.awt.Color(255, 255, 255));
        btn_Image.setText("Choose Image");
        btn_Image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ImageActionPerformed(evt);
            }
        });
        jPanel22.add(btn_Image, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 390, 180, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, 1544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelHome1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHome1MouseClicked
        // TODO add your handling code here:
        DoctorsModule rm = new DoctorsModule();
        rm.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelHome1MouseClicked

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLnameActionPerformed

    private void txtSearch1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearch1MouseClicked
        // TODO add your handling code here:
        txtSearch1.setText("");
    }//GEN-LAST:event_txtSearch1MouseClicked

    private void txtSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearch1ActionPerformed

    private void rdoMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoMaleActionPerformed

    private void cmboStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmboStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmboStatusActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String fname = txtFname.getText();
        String lname = txtLname.getText();

        String sex = "";
        if (rdoMale.isSelected()) {
            sex = "Male";
        }
        if (rdoFemale.isSelected()) {
            sex = "Female";
        }

        String bdate = txtBdate.getText();
        String username = txtUsername.getText();
        String password = txtPassword.getText();
        String address = txtAddress.getText();
        //SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-mm-dd");
        //String bdate = dateformat.format(Bdate.getText()/*getDate()*/);

        String phone = txtPhone.getText();

        String status = "";
        if (cmboStatus.getSelectedItem().equals("Single")) {
            status = "Single";
        }
        if (cmboStatus.getSelectedItem().equals("Married")) {
            status = "Married";
        }
        if (cmboStatus.getSelectedItem().equals("Divorced")) {
            status = "Divorced";
        }
        if (cmboStatus.getSelectedItem().equals("Widow")) {
            status = "Widow";
        }

        String email = txtEmail.getText();
        String contract = txtContract.getText();
        String date = txtDate.getText();
        
        if(ImgPath != null){
            try {
                InputStream img = new FileInputStream(ImgPath);
                String UpdateQuery = "UPDATE doc_registration SET image = ? WHERE u_id = ?";
                int id = Integer.parseInt(txtSearch1.getText());
                PreparedStatement ps = getConnection().prepareStatement(UpdateQuery);
                ps.setBlob(1, img);
                ps.setInt(2, id);
                if(ps.executeUpdate() == 1){
                    JOptionPane.showMessageDialog(null,"Image Updated");
                }
                else{
                    JOptionPane.showMessageDialog(null,"No Image exist with this id");
                }
            } catch (FileNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(null,ex);
            }
        }

        Doctors2 n = new Doctors2();
        if(n.updateInfo(fname,lname,sex,bdate,username,password,address,phone,status,email,contract,date)){
            JOptionPane.showMessageDialog(null,"Successfully updated the record!");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed
        // TODO add your handling code here:
        String id = txtSearch1.getText();
        Doctors2 ad = new Doctors2();
        ResultSet res = ad.getInfo(id);

        try {
            res.beforeFirst();
            while (res.next()) {
                
                txtSearch1.setText(res.getString("u_id"));
                txtFname.setText(res.getString("u_fname"));
                txtLname.setText(res.getString("u_lname"));

                String sex = res.getString("u_sex");
                if (sex.equals("Male")) {
                    rdoMale.setSelected(true);
                } else if (sex.equals("Female")) {
                    rdoFemale.setSelected(true);
                }

                txtBdate.setText(res.getString("u_bdate"));
                txtUsername.setText(res.getString("u_username"));
                txtPassword.setText(res.getString("u_pass"));
                txtContract.setText(res.getString("u_contract"));

                String status = res.getString("u_status");
                if (status.equals("Single")) {
                    cmboStatus.getModel().setSelectedItem("Single");
                } else if (status.equals("Married")) {
                    cmboStatus.getModel().setSelectedItem("Married");
                } else if (status.equals("Divorced")) {
                    cmboStatus.getModel().setSelectedItem("Divorced");
                } else if (status.equals("Widow")) {
                    cmboStatus.getModel().setSelectedItem("Widow");
                }

                byte[] img = res.getBytes("image");
                ImageIcon image = new ImageIcon(img);
                Image im = image.getImage();
                Image myImg = im.getScaledInstance(lbl_image.getWidth(),lbl_image.getHeight(),Image.SCALE_SMOOTH);
                ImageIcon newImage = new ImageIcon(myImg);
                lbl_image.setIcon(newImage);
                
                txtEmail.setText(res.getString("u_email"));
                txtPhone.setText(res.getString("u_phone"));
                txtAddress.setText(res.getString("u_address"));
                txtDate.setText(res.getString("u_dregistered"));

            }
        } catch (SQLException ex) {
            Logger.getLogger(Doctor_Profile.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,ex);
        }
        btnClear.setEnabled(true);
        btnUpdate.setEnabled(true);
    }//GEN-LAST:event_btnSearch1ActionPerformed

    private void txtFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFnameActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtSearch1.setText("");
        txtFname.setText("");
        txtLname.setText("");
        buttonGroup1.clearSelection();
        txtBdate.setText("");
        cmboStatus.getModel().setSelectedItem("Select");
        txtAddress.setText("");
        txtPhone.setText("");
        txtEmail.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
        txtContract.setText("");
        txtDate.setText("");
        
        ImageIcon ad = new ImageIcon(getClass().getResource("doctor.png"));
        Image image = ad.getImage().getScaledInstance(160, 160, Image.SCALE_SMOOTH);
        lbl_image.setIcon(new ImageIcon(image));

        btnClear.setEnabled(false);
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btn_ImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ImageActionPerformed
       try{
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));

        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.images", "jpg", "png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            lbl_image.setIcon(ResizeImage(path, null));
            ImgPath = path;
        } else {
            JOptionPane.showMessageDialog(null, "No File Selected!");
        }
       }catch(Exception ex){
           JOptionPane.showMessageDialog(null, ex);
       }
    }//GEN-LAST:event_btn_ImageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctor_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctor_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctor_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctor_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctor_Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSearch1;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btn_Image;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmboStatus;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabelHome1;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JLabel lbl_image1;
    private javax.swing.JRadioButton rdoFemale;
    private javax.swing.JRadioButton rdoMale;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBdate;
    private javax.swing.JTextField txtContract;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSearch1;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
