/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PatientsInfo;

import Cashier.Billing;
import Doctor.Doctors;
import Laboratory.MedicalLaboratory;
import Nurse.Nurse;
import Receptionist.Receptionist;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author kli ann
 */
public class AdminPortal extends javax.swing.JFrame {
    /**
     * Creates new form AdminPortal
     */
    public AdminPortal() {
        initComponents();
        ImageIcon ad = new ImageIcon(getClass().getResource("admin.jpg")); 
        Image image = ad.getImage().getScaledInstance(100, 120, Image.SCALE_SMOOTH);
        jLabelAdmin.setIcon(new ImageIcon(image) );
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabelAdmin = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanelReceptionist = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanelDocdetails = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanelAppointments = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanelPrescription = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanelNurse = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanelCashier = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jPanelLab = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanelInPatients = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelPatientsDetails = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 38)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Admin Portal");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jLabelAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PatientsInfo/admin.jpg"))); // NOI18N
        jPanel2.add(jLabelAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 100));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PatientsInfo/logout1.png"))); // NOI18N
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 20, 50, 50));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Logout");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 70, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1436, 100));

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Welcome");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("to");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Admin's Portal");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 240, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 260, 470));

        jPanelReceptionist.setBackground(new java.awt.Color(255, 255, 255));
        jPanelReceptionist.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelReceptionist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelReceptionistMouseClicked(evt);
            }
        });
        jPanelReceptionist.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Receptionist");
        jPanelReceptionist.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Receptionist/receptionist.jpg"))); // NOI18N
        jPanelReceptionist.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 180, 180));

        jPanel1.add(jPanelReceptionist, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 250, 230));

        jPanelDocdetails.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDocdetails.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelDocdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelDocdetailsMouseClicked(evt);
            }
        });
        jPanelDocdetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Doctor Details");
        jPanelDocdetails.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PatientsInfo/doc.png"))); // NOI18N
        jPanelDocdetails.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, 170));

        jPanel1.add(jPanelDocdetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 150, 240, 230));

        jPanelAppointments.setBackground(new java.awt.Color(255, 255, 255));
        jPanelAppointments.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelAppointments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAppointmentsMouseClicked(evt);
            }
        });
        jPanelAppointments.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Appointments");
        jPanelAppointments.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PatientsInfo/appointment.jpg"))); // NOI18N
        jPanelAppointments.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.add(jPanelAppointments, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 240, 220));

        jPanelPrescription.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPrescription.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelPrescription.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelPrescriptionMouseClicked(evt);
            }
        });
        jPanelPrescription.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("Prescription");
        jPanelPrescription.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 140, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PatientsInfo/presc3.png"))); // NOI18N
        jPanelPrescription.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 210, 160));

        jPanel1.add(jPanelPrescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 400, 240, 220));

        jPanelNurse.setBackground(new java.awt.Color(255, 255, 255));
        jPanelNurse.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelNurse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelNurseMouseClicked(evt);
            }
        });
        jPanelNurse.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("Nurse Details");
        jPanelNurse.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PatientsInfo/nurse.png"))); // NOI18N
        jPanelNurse.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 170, 170));

        jPanel1.add(jPanelNurse, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 150, 230, 230));

        jPanelCashier.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCashier.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelCashier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCashierMouseClicked(evt);
            }
        });
        jPanelCashier.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 153, 153));
        jLabel17.setText("Billings");
        jPanelCashier.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PatientsInfo/cashier.png"))); // NOI18N
        jPanelCashier.add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 170, 190));

        jPanel1.add(jPanelCashier, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 250, 220));

        jPanelLab.setBackground(new java.awt.Color(255, 255, 255));
        jPanelLab.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLabMouseClicked(evt);
            }
        });
        jPanelLab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PatientsInfo/laboratories.png"))); // NOI18N
        jPanelLab.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 180));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 153, 153));
        jLabel19.setText("Laboratory Test");
        jPanelLab.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jPanel1.add(jPanelLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 400, 230, 220));

        jPanelInPatients.setBackground(new java.awt.Color(255, 255, 255));
        jPanelInPatients.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelInPatients.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelInPatients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelInPatientsMouseClicked(evt);
            }
        });
        jPanelInPatients.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PatientsInfo/bd.jpg"))); // NOI18N
        jPanelInPatients.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 180));

        jLabelPatientsDetails.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelPatientsDetails.setForeground(new java.awt.Color(0, 153, 153));
        jLabelPatientsDetails.setText(" Patient Details");
        jLabelPatientsDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelPatientsDetails.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jLabelPatientsDetailsFocusLost(evt);
            }
        });
        jLabelPatientsDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPatientsDetailsMouseClicked(evt);
            }
        });
        jPanelInPatients.add(jLabelPatientsDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jPanel1.add(jPanelInPatients, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 240, 230));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 242, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelReceptionistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelReceptionistMouseClicked
        // TODO add your handling code here:
        Receptionist r = new Receptionist();
        r.setVisible(true);
        dispose();
    }//GEN-LAST:event_jPanelReceptionistMouseClicked

    private void jPanelDocdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDocdetailsMouseClicked
        // TODO add your handling code here:
        
        new Doctors().setVisible(true);
        dispose();
    }//GEN-LAST:event_jPanelDocdetailsMouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
        int lg = JOptionPane.showConfirmDialog(null, "Are you sure you want to Log out?","Ädmin's Portal", JOptionPane.YES_NO_OPTION);
        if (lg==0){
             new Home().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jPanelCashierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCashierMouseClicked
        // TODO add your handling code here:
        Billing b = new Billing();
        b.setVisible(true);
        dispose();
    }//GEN-LAST:event_jPanelCashierMouseClicked

    private void jLabelPatientsDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPatientsDetailsMouseClicked
        // TODO add your handling code here:
        new InPatient().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelPatientsDetailsMouseClicked

    private void jLabelPatientsDetailsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabelPatientsDetailsFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelPatientsDetailsFocusLost

    private void jPanelInPatientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelInPatientsMouseClicked
        // TODO add your handling code here:
        InPatient in = new InPatient();
        in.setVisible(true);
        dispose();
    }//GEN-LAST:event_jPanelInPatientsMouseClicked

    private void jPanelNurseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelNurseMouseClicked
        // TODO add your handling code here:
        new Nurse().setVisible(true);
        dispose();
    }//GEN-LAST:event_jPanelNurseMouseClicked

    private void jPanelPrescriptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPrescriptionMouseClicked
        // TODO add your handling code here:
        new Prescription().setVisible(true);
        dispose();
    }//GEN-LAST:event_jPanelPrescriptionMouseClicked

    private void jPanelAppointmentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAppointmentsMouseClicked
        // TODO add your handling code here:
         new Appointments().setVisible(true);
         dispose();
    }//GEN-LAST:event_jPanelAppointmentsMouseClicked

    private void jPanelLabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLabMouseClicked
        MedicalLaboratory ml = new MedicalLaboratory();
        ml.setVisible(true);
        dispose();
    }//GEN-LAST:event_jPanelLabMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPortal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAdmin;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelPatientsDetails;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelAppointments;
    private javax.swing.JPanel jPanelCashier;
    private javax.swing.JPanel jPanelDocdetails;
    private javax.swing.JPanel jPanelInPatients;
    private javax.swing.JPanel jPanelLab;
    private javax.swing.JPanel jPanelNurse;
    private javax.swing.JPanel jPanelPrescription;
    private javax.swing.JPanel jPanelReceptionist;
    // End of variables declaration//GEN-END:variables
}
