/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ReceptionistPortal;

import Login.MyConnection;
import PatientsInfo.Clinical2;
import PatientsInfo.InPatient2;
import java.awt.Image;
import java.awt.print.PrinterException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kli ann
 */
public class ClinicalDataR extends javax.swing.JFrame {
private JFrame frame;
    /**
     * Creates new form ClinicalDataR
     */
    public ClinicalDataR() {
        initComponents();
        btnClear1.setEnabled(false);
        
        btnUpdate.setEnabled(false);
        btnClear2.setEnabled(false);
        
        btnDelete.setEnabled(false);
        btnClear.setEnabled(false);
        btnPrint.setEnabled(false);
        btnDisplay.setEnabled(false);
        ImageIcon ad = new ImageIcon(getClass().getResource("bd.jpg")); 
        Image image = ad.getImage().getScaledInstance(110, 130, Image.SCALE_SMOOTH);
        Logo.setIcon(new ImageIcon(image) );
        Logo1.setIcon(new ImageIcon(image) );
        Logo2.setIcon(new ImageIcon(image) );
        Logo3.setIcon(new ImageIcon(image) );
        
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        //for displaying data from table in Mysql
        DefaultTableModel model = (DefaultTableModel) tblRecords.getModel();
        model.setRowCount(0);
        
        InPatient2 pr = new InPatient2();
        ResultSet res = null;
        try{
            res = pr.getVital();
            res.beforeFirst();
            while(res.next()){
                model.addRow(new Object[]{Integer.parseInt(res.getString(1)),res.getString(2),Integer.parseInt(res.getString(3)),res.getString(4),res.getString(5),res.getString(6),res.getString(7),res.getString(8),res.getString(9),res.getString(10)});
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Cannot display" + e.toString());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtPhysicalAppearance1 = new javax.swing.JTextField();
        txtTemp1 = new javax.swing.JTextField();
        txtComplaint1 = new javax.swing.JTextField();
        txtPresentIllness1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnClear1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtBP1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtWeight1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtHeight1 = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        txtName1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtPhysician1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabelArrow1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtPhysicalAppearance2 = new javax.swing.JTextField();
        txtTemp2 = new javax.swing.JTextField();
        txtComplaint2 = new javax.swing.JTextField();
        txtPresentIllness2 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        btnClear2 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        txtBP2 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtWeight2 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtHeight2 = new javax.swing.JTextField();
        txtSearch1 = new javax.swing.JTextField();
        btnSearch1 = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        Logo1 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txtName2 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        txtPhysician2 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnDisplay = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPhysicalAppearance = new javax.swing.JTextField();
        txtTemp = new javax.swing.JTextField();
        txtComplaint = new javax.swing.JTextField();
        txtPresentIllness = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtBP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtHeight = new javax.swing.JTextField();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Logo2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtClinicalData = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPhysician = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        Logo3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRecords = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 153));
        jLabel14.setText("Present Illness:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 153));
        jLabel15.setText("Physical Appearance:");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, -1, -1));

        txtPhysicalAppearance1.setBackground(new java.awt.Color(204, 255, 255));
        txtPhysicalAppearance1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhysicalAppearance1ActionPerformed(evt);
            }
        });
        jPanel3.add(txtPhysicalAppearance1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, 230, 60));

        txtTemp1.setBackground(new java.awt.Color(204, 255, 255));
        txtTemp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTemp1ActionPerformed(evt);
            }
        });
        jPanel3.add(txtTemp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, 230, 30));

        txtComplaint1.setBackground(new java.awt.Color(204, 255, 255));
        txtComplaint1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComplaint1ActionPerformed(evt);
            }
        });
        jPanel3.add(txtComplaint1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 230, 60));

        txtPresentIllness1.setBackground(new java.awt.Color(204, 255, 255));
        txtPresentIllness1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPresentIllness1ActionPerformed(evt);
            }
        });
        jPanel3.add(txtPresentIllness1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, 230, 50));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 153));
        jLabel16.setText("Complaint:");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, -1, -1));

        btnClear1.setBackground(new java.awt.Color(0, 153, 153));
        btnClear1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnClear1.setForeground(new java.awt.Color(255, 255, 255));
        btnClear1.setText("CLEAR");
        btnClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnClear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 460, 120, 40));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 153, 153));
        jLabel17.setText("Temperature:");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, -1, -1));

        txtBP1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.add(txtBP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 230, 40));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 153, 153));
        jLabel18.setText("BP:");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, -1, -1));

        txtWeight1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.add(txtWeight1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 230, 40));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 153, 153));
        jLabel19.setText("Weight:");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 153, 153));
        jLabel20.setText("Patient ID:");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, 20));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 153, 153));
        jLabel21.setText("Height:");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, -1, -1));

        txtHeight1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.add(txtHeight1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 230, 40));

        txtID.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 230, 40));

        btnAdd.setBackground(new java.awt.Color(0, 153, 153));
        btnAdd.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel3.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 110, 130, 40));

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("CLINICAL DATA");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("(Vital Signs)");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PatientsInfo/bd.jpg"))); // NOI18N
        jPanel4.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 90));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 90));

        txtName1.setBackground(new java.awt.Color(204, 255, 255));
        txtName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtName1ActionPerformed(evt);
            }
        });
        jPanel3.add(txtName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 230, 40));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 153, 153));
        jLabel25.setText("Full Name:");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        txtPhysician1.setBackground(new java.awt.Color(204, 255, 255));
        txtPhysician1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhysician1ActionPerformed(evt);
            }
        });
        jPanel3.add(txtPhysician1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 230, 40));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 153, 153));
        jLabel26.setText("Physician:");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, -1, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), new java.awt.Color(0, 204, 204)));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PatientsInfo/user1.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addContainerGap())
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 210, 220, 210));

        jLabelArrow1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PatientsInfo/arrow1.png"))); // NOI18N
        jLabelArrow1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelArrow1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelArrow1MouseClicked(evt);
            }
        });
        jPanel3.add(jLabelArrow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 90, -1));

        jTabbedPane1.addTab("Add ClinicalData", jPanel3);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 153, 153));
        jLabel24.setText("Present Illness:");
        jPanel7.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 153, 153));
        jLabel28.setText("Physical Appearance:");
        jPanel7.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, -1, -1));

        txtPhysicalAppearance2.setBackground(new java.awt.Color(204, 255, 255));
        txtPhysicalAppearance2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhysicalAppearance2ActionPerformed(evt);
            }
        });
        jPanel7.add(txtPhysicalAppearance2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, 230, 70));

        txtTemp2.setBackground(new java.awt.Color(204, 255, 255));
        txtTemp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTemp2ActionPerformed(evt);
            }
        });
        jPanel7.add(txtTemp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, 230, 30));

        txtComplaint2.setBackground(new java.awt.Color(204, 255, 255));
        txtComplaint2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComplaint2ActionPerformed(evt);
            }
        });
        jPanel7.add(txtComplaint2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 230, 70));

        txtPresentIllness2.setBackground(new java.awt.Color(204, 255, 255));
        txtPresentIllness2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPresentIllness2ActionPerformed(evt);
            }
        });
        jPanel7.add(txtPresentIllness2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, 230, 60));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 153, 153));
        jLabel29.setText("Complaint:");
        jPanel7.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));

        btnClear2.setBackground(new java.awt.Color(0, 153, 153));
        btnClear2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnClear2.setForeground(new java.awt.Color(255, 255, 255));
        btnClear2.setText("CLEAR");
        btnClear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear2ActionPerformed(evt);
            }
        });
        jPanel7.add(btnClear2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 540, 130, 40));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 153, 153));
        jLabel30.setText("Temperature:");
        jPanel7.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, -1, -1));

        txtBP2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel7.add(txtBP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 230, 30));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 153, 153));
        jLabel31.setText("BP:");
        jPanel7.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, -1, -1));

        txtWeight2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel7.add(txtWeight2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 230, 30));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 153, 153));
        jLabel32.setText("Weight:");
        jPanel7.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 153, 153));
        jLabel33.setText("Patient ID:");
        jPanel7.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, 20));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 153, 153));
        jLabel34.setText("Height:");
        jPanel7.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        txtHeight2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel7.add(txtHeight2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 230, 30));

        txtSearch1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel7.add(txtSearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 190, 30));

        btnSearch1.setBackground(new java.awt.Color(0, 153, 153));
        btnSearch1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnSearch1.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch1.setText("Search");
        btnSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch1ActionPerformed(evt);
            }
        });
        jPanel7.add(btnSearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 90, 30));

        btnUpdate.setBackground(new java.awt.Color(0, 153, 153));
        btnUpdate.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel7.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 540, 130, 40));

        jPanel8.setBackground(new java.awt.Color(0, 204, 204));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("CLINICAL DATA");
        jPanel8.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, 30));

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("(Vital Signs)");
        jPanel8.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        Logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PatientsInfo/bd.jpg"))); // NOI18N
        jPanel8.add(Logo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 90));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 90));

        jLabel37.setForeground(new java.awt.Color(0, 204, 204));
        jLabel37.setText("________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________");
        jPanel7.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, 70));

        txtName2.setBackground(new java.awt.Color(204, 255, 255));
        txtName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtName2ActionPerformed(evt);
            }
        });
        jPanel7.add(txtName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 230, 30));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 153, 153));
        jLabel38.setText("Full Name:");
        jPanel7.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        txtPhysician2.setBackground(new java.awt.Color(204, 255, 255));
        txtPhysician2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhysician2ActionPerformed(evt);
            }
        });
        jPanel7.add(txtPhysician2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, 230, 30));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 153, 153));
        jLabel39.setText("Physician:");
        jPanel7.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, -1, -1));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), new java.awt.Color(0, 204, 204)));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PatientsInfo/user1.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel40)
                .addContainerGap())
        );

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 210, 220, 210));

        jTabbedPane1.addTab("Update Clinical", jPanel7);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDisplay.setBackground(new java.awt.Color(0, 153, 153));
        btnDisplay.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnDisplay.setForeground(new java.awt.Color(255, 255, 255));
        btnDisplay.setText("Display");
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });
        jPanel1.add(btnDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 520, 120, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 153));
        jLabel9.setText("Present Illness:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Physical Appearance:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, -1, -1));

        txtPhysicalAppearance.setBackground(new java.awt.Color(204, 255, 255));
        txtPhysicalAppearance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhysicalAppearanceActionPerformed(evt);
            }
        });
        jPanel1.add(txtPhysicalAppearance, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 410, 230, 70));

        txtTemp.setBackground(new java.awt.Color(204, 255, 255));
        txtTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTempActionPerformed(evt);
            }
        });
        jPanel1.add(txtTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 230, 30));

        txtComplaint.setBackground(new java.awt.Color(204, 255, 255));
        txtComplaint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComplaintActionPerformed(evt);
            }
        });
        jPanel1.add(txtComplaint, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 230, 70));

        txtPresentIllness.setBackground(new java.awt.Color(204, 255, 255));
        txtPresentIllness.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPresentIllnessActionPerformed(evt);
            }
        });
        jPanel1.add(txtPresentIllness, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 230, 60));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 153));
        jLabel8.setText("Complaint:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        btnPrint.setBackground(new java.awt.Color(0, 153, 153));
        btnPrint.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(255, 255, 255));
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 520, 120, 40));

        btnClear.setBackground(new java.awt.Color(0, 153, 153));
        btnClear.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, 120, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jLabel7.setText("Temperature:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, -1, -1));

        txtBP.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.add(txtBP, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 230, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("BP:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        txtWeight.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.add(txtWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 230, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("Weight:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Patient ID:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 153));
        jLabel10.setText("Height:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        txtHeight.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.add(txtHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 230, 30));

        txtSearch.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 190, 30));

        btnSearch.setBackground(new java.awt.Color(0, 153, 153));
        btnSearch.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 90, 30));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CLINICAL DATA");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("(Vital Signs)");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        Logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PatientsInfo/bd.jpg"))); // NOI18N
        jPanel2.add(Logo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 90));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 90));

        txtClinicalData.setColumns(20);
        txtClinicalData.setRows(5);
        jScrollPane1.setViewportView(txtClinicalData);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 180, 480, 460));

        jLabel12.setForeground(new java.awt.Color(0, 204, 204));
        jLabel12.setText("________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, 70));

        txtName.setBackground(new java.awt.Color(204, 255, 255));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 230, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 153));
        jLabel11.setText("Full Name:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        txtPhysician.setBackground(new java.awt.Color(204, 255, 255));
        txtPhysician.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhysicianActionPerformed(evt);
            }
        });
        jPanel1.add(txtPhysician, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 230, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 153));
        jLabel13.setText("Physician:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, -1, -1));

        btnDelete.setBackground(new java.awt.Color(0, 153, 153));
        btnDelete.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, 120, 40));

        jTabbedPane1.addTab("Delete ClinicalData", jPanel1);

        jPanel11.setBackground(new java.awt.Color(204, 255, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(0, 204, 204));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Patients Vital Signs");
        jPanel12.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        Logo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PatientsInfo/bd.jpg"))); // NOI18N
        jPanel12.add(Logo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 100));

        jPanel11.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1483, 92));

        tblRecords.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PatientID", " Name", "Height", "Weight", "BP", "Temperature", "Complaint", "Physician", "PresentIllness", "PhysicalAppearance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblRecords);

        jPanel11.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 1260, 510));

        jTabbedPane1.addTab("All ClinicalRecords", jPanel11);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1445, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPhysicalAppearance1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhysicalAppearance1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhysicalAppearance1ActionPerformed

    private void txtTemp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTemp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTemp1ActionPerformed

    private void txtComplaint1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComplaint1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComplaint1ActionPerformed

    private void txtPresentIllness1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPresentIllness1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPresentIllness1ActionPerformed

    private void btnClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear1ActionPerformed
        // TODO add your handling code here:

        txtID.setText("");
        txtName1.setText("");
        txtHeight1.setText("");
        txtWeight1.setText("");
        txtBP1.setText("");
        txtTemp1.setText("");
        txtComplaint1.setText("");
        txtPhysician1.setText("");
        txtPresentIllness1.setText("");
        txtPhysicalAppearance1.setText("");

        btnClear1.setEnabled(false);
    }//GEN-LAST:event_btnClear1ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String id = txtID.getText();
        String name = txtName1.getText();
        String height = txtHeight1.getText();
        String weight = txtWeight1.getText();
        String bp = txtBP1.getText();
        String temperature = txtTemp1.getText();
        String complaint = txtComplaint1.getText();
        String physician = txtPhysician1.getText();
        String presentillness = txtPresentIllness1.getText();
        String physical = txtPhysicalAppearance1.getText();

        Clinical2 c = new Clinical2(id,name,height,weight,bp,temperature, complaint,physician,presentillness,physical);
        if(id.isEmpty()){
            JOptionPane.showMessageDialog(null," Please enter Patient id");
        }
        else if (checkId(id)) {
            JOptionPane.showMessageDialog(null, "Patient ID already exist!\n Please try another one.");
        }
        else if(name.isEmpty()){
            JOptionPane.showMessageDialog(null," Please enter patients name");
        }
        else if(height.isEmpty()){
            JOptionPane.showMessageDialog(null," Please enter patients height");
        }
        else if(weight.isEmpty()){
            JOptionPane.showMessageDialog(null," Please enter patients weight");
        }
        else if(bp.isEmpty()){
            JOptionPane.showMessageDialog(null," Please enter patients blood pressure");
        }
        else if(temperature.isEmpty()){
            JOptionPane.showMessageDialog(null," Please enter patients temperature");
        }
        else if(complaint.isEmpty()){
            JOptionPane.showMessageDialog(null," Please enter patients complaint");
        }
        else if(physician.isEmpty()){
            JOptionPane.showMessageDialog(null," Please enter physician");
        }
        else if(presentillness.isEmpty()){
            JOptionPane.showMessageDialog(null," Please enter patients present illness");
        }
        else if(physical.isEmpty()){
            JOptionPane.showMessageDialog(null," Please enter patients physical appearance");
        }
        else if(c.addNew()){
            JOptionPane.showMessageDialog(null," Patients vital signs added!");
        }

        btnClear1.setEnabled(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName1ActionPerformed

    private void txtPhysician1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhysician1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhysician1ActionPerformed

    private void jLabelArrow1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelArrow1MouseClicked
        // TODO add your handling code here:
        new InPatientR().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelArrow1MouseClicked

    private void txtPhysicalAppearance2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhysicalAppearance2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhysicalAppearance2ActionPerformed

    private void txtTemp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTemp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTemp2ActionPerformed

    private void txtComplaint2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComplaint2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComplaint2ActionPerformed

    private void txtPresentIllness2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPresentIllness2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPresentIllness2ActionPerformed

    private void btnClear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear2ActionPerformed
        // TODO add your handling code here:

        txtSearch1.setText("");
        txtName2.setText("");
        txtHeight2.setText("");
        txtWeight2.setText("");
        txtBP2.setText("");
        txtTemp2.setText("");
        txtComplaint2.setText("");
        txtPhysician2.setText("");
        txtPresentIllness2.setText("");
        txtPhysicalAppearance2.setText("");

        btnUpdate.setEnabled(false);
        btnClear2.setEnabled(false);
    }//GEN-LAST:event_btnClear2ActionPerformed

    private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed
        // TODO add your handling code here:
        String id = txtSearch1.getText();
        Clinical2 cd = new Clinical2();
        ResultSet res = cd.getInfo(id);

        try {
            res.beforeFirst();
            while(res.next()){
                txtSearch1.setText(res.getString("PatientId"));

                txtName2.setText(res.getString("FullName"));
                txtHeight2.setText(res.getString("Height"));
                txtWeight2.setText(res.getString("Weight"));
                txtBP2.setText(res.getString("BP"));
                txtComplaint2.setText(res.getString("Complaint"));
                txtTemp2.setText(res.getString("Temperature"));
                txtPhysician2.setText(res.getString("Physician"));
                txtPresentIllness2.setText(res.getString("PresentIllness"));
                txtPhysicalAppearance2.setText(res.getString("PhysicalAppearance"));

            }
            while(res.next()){
                txtSearch1.setText(res.getString(""));
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Id does not exist!");
        }
        btnUpdate.setEnabled(true);
        btnClear2.setEnabled(true);
    }//GEN-LAST:event_btnSearch1ActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String id = txtSearch1.getText();
        String name = txtName2.getText();
        String height = txtHeight2.getText();
        String weight = txtWeight2.getText();
        String bp = txtBP2.getText();
        String complaint = txtComplaint2.getText();
        String physician = txtPhysician2.getText();
        String temp = txtTemp2.getText();
        String presentillness = txtPresentIllness2.getText();
        String physical = txtPhysicalAppearance2.getText();

        Clinical2 cd = new Clinical2();
        if(id.isEmpty()){
            JOptionPane.showMessageDialog(null," Unable to update! Please search Patient ID to update patient vital status");
        }
        else if(name.isEmpty()){
            JOptionPane.showMessageDialog(null," Please enter patients name");
        }
        else if(height.isEmpty()){
            JOptionPane.showMessageDialog(null," Please enter patients height");
        }
        else if(weight.isEmpty()){
            JOptionPane.showMessageDialog(null," Please enter patients weight");
        }
        else if(bp.isEmpty()){
            JOptionPane.showMessageDialog(null," Please enter patients blood pressure");
        }
        else if(temp.isEmpty()){
            JOptionPane.showMessageDialog(null," Please enter patients temperature");
        }
        else if(complaint.isEmpty()){
            JOptionPane.showMessageDialog(null," Please enter patients complaint");
        }
        else if(physician.isEmpty()){
            JOptionPane.showMessageDialog(null," Please enter physician");
        }
        else if(presentillness.isEmpty()){
            JOptionPane.showMessageDialog(null," Please enter patients present illness");
        }
        else if(physical.isEmpty()){
            JOptionPane.showMessageDialog(null," Please enter patients physical appearance");
        }
        else if(cd.updateInfo(id,name,height,weight,bp,complaint,physician,temp,presentillness,physical)){
            JOptionPane.showMessageDialog(null,"Successfully updated the record!");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName2ActionPerformed

    private void txtPhysician2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhysician2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhysician2ActionPerformed

    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayActionPerformed
        String id = txtSearch.getText();
        Clinical2 cd = new Clinical2();
        ResultSet res = cd.getInfo(id);

        try {
            res.beforeFirst();
            while(res.next()){

                String name = res.getString("FullName");
                String height = res.getString("Height");
                String weight = res.getString("Weight");
                String bp = res.getString("BP");
                String comp = res.getString("Complaint");
                String temp = res.getString("Temperature");
                String physician = res.getString("Physician");
                String p = res.getString("PresentIllness");
                String pa = res.getString("PhysicalAppearance");

                txtClinicalData.append("\n\t\tPatients Vital Signs\n\n"
                    +"\n\t Full Name: \t\t" + name
                    +"\n\t Height: \t\t" + height
                    +"\n\t Weight: \t\t" + weight
                    +"\n\t BP: \t\t" + bp
                    +"\n\t Complaint: \t\t" + comp
                    +"\n\t Temperature: \t\t" + temp
                    +"\n\t Physician: \t\t" + physician
                    +"\n\t Present Illness: \t" + p
                    +"\n\t Physical Appearance: \t" + pa
                    +"\n\n\n\n\t\n\t\n\t");
            }
            while(res.next()){
                txtSearch.setText(res.getString(""));
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Id does not exist!");
        }
    }//GEN-LAST:event_btnDisplayActionPerformed

    private void txtPhysicalAppearanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhysicalAppearanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhysicalAppearanceActionPerformed

    private void txtTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTempActionPerformed

    private void txtComplaintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComplaintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComplaintActionPerformed

    private void txtPresentIllnessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPresentIllnessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPresentIllnessActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        try{
            txtClinicalData.print();
        }catch (PrinterException ex){
            Logger.getLogger(ClinicalDataR.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:

        txtSearch.setText("");
        txtName.setText("");
        txtClinicalData.setText("");
        txtHeight.setText("");
        txtWeight.setText("");
        txtBP.setText("");
        txtTemp.setText("");
        txtComplaint.setText("");
        txtPhysician.setText("");
        txtPresentIllness.setText("");
        txtPhysicalAppearance.setText("");

        btnDelete.setEnabled(false);
        btnClear.setEnabled(false);
        btnPrint.setEnabled(false);
        btnDisplay.setEnabled(false);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        btnDelete.setEnabled(true);
        btnClear.setEnabled(true);
        btnPrint.setEnabled(true);
        btnDisplay.setEnabled(true);

        String id = txtSearch.getText();
        Clinical2 cd = new Clinical2();
        ResultSet res = cd.getInfo(id);

        try {
            res.beforeFirst();
            while(res.next()){
                txtSearch.setText(res.getString("PatientId"));

                txtName.setText(res.getString("FullName"));
                txtHeight.setText(res.getString("Height"));
                txtWeight.setText(res.getString("Weight"));
                txtBP.setText(res.getString("BP"));
                txtComplaint.setText(res.getString("Complaint"));
                txtTemp.setText(res.getString("Temperature"));
                txtPhysician.setText(res.getString("Physician"));
                txtPresentIllness.setText(res.getString("PresentIllness"));
                txtPhysicalAppearance.setText(res.getString("PhysicalAppearance"));

            }
            while(res.next()){
                txtSearch.setText(res.getString(""));
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Id does not exist!");
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtPhysicianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhysicianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhysicianActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:

        String id = txtSearch.getText();
        InPatient2 reg = new InPatient2();
        if(reg.deleteVital(id)){
            JOptionPane.showConfirmDialog(frame,"Are you sure you want to delete patient's vital signs?","Hospital Management System",JOptionPane.YES_NO_OPTION);
        }
        JOptionPane.showMessageDialog(null,"deletion completed!");

        txtSearch.setText("");
        txtName.setText("");
        txtClinicalData.setText("");
        txtHeight.setText("");
        txtWeight.setText("");
        txtBP.setText("");
        txtTemp.setText("");
        txtComplaint.setText("");
        txtPhysician.setText("");
        txtPresentIllness.setText("");
        txtPhysicalAppearance.setText("");

        btnDelete.setEnabled(false);
        btnClear.setEnabled(false);
        btnPrint.setEnabled(false);
        btnDisplay.setEnabled(false);
    }//GEN-LAST:event_btnDeleteActionPerformed

    //function to check if the patient ID already exist
    public boolean checkId(String id) {
        PreparedStatement ps;
        ResultSet rs;
        boolean checkid = false;

        String query = "SELECT * FROM `clinical` WHERE `PatientId` =?";

        try {
            ps = MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, id);

            rs = ps.executeQuery();

            if (rs.next()) {
                checkid = true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(ClinicalDataR.class.getName()).log(Level.SEVERE, null, ex);
        }
        return checkid;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClinicalDataR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClinicalDataR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClinicalDataR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClinicalDataR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClinicalDataR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Logo1;
    private javax.swing.JLabel Logo2;
    private javax.swing.JLabel Logo3;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClear1;
    private javax.swing.JButton btnClear2;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDisplay;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearch1;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelArrow1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblRecords;
    private javax.swing.JTextField txtBP;
    private javax.swing.JTextField txtBP1;
    private javax.swing.JTextField txtBP2;
    private javax.swing.JTextArea txtClinicalData;
    private javax.swing.JTextField txtComplaint;
    private javax.swing.JTextField txtComplaint1;
    private javax.swing.JTextField txtComplaint2;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtHeight1;
    private javax.swing.JTextField txtHeight2;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtName1;
    private javax.swing.JTextField txtName2;
    private javax.swing.JTextField txtPhysicalAppearance;
    private javax.swing.JTextField txtPhysicalAppearance1;
    private javax.swing.JTextField txtPhysicalAppearance2;
    private javax.swing.JTextField txtPhysician;
    private javax.swing.JTextField txtPhysician1;
    private javax.swing.JTextField txtPhysician2;
    private javax.swing.JTextField txtPresentIllness;
    private javax.swing.JTextField txtPresentIllness1;
    private javax.swing.JTextField txtPresentIllness2;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSearch1;
    private javax.swing.JTextField txtTemp;
    private javax.swing.JTextField txtTemp1;
    private javax.swing.JTextField txtTemp2;
    private javax.swing.JTextField txtWeight;
    private javax.swing.JTextField txtWeight1;
    private javax.swing.JTextField txtWeight2;
    // End of variables declaration//GEN-END:variables
}
