/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ReceptionistPortal;

import Login.MyConnection;
import Login.Registration;
import PatientsInfo.InPatient2;
import java.awt.Frame;
import java.awt.Image;
import java.awt.print.PrinterException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author kli ann
 */
public class InPatientR extends javax.swing.JFrame {

    /**
     * Creates new form InPatient
     */
    public InPatientR() {
        initComponents();
        
        ImageIcon ad = new ImageIcon(getClass().getResource("bd.jpg")); 
        Image image = ad.getImage().getScaledInstance(110, 110, Image.SCALE_SMOOTH);
        LogoAdd.setIcon(new ImageIcon(image) );
        LogoUpdate.setIcon(new ImageIcon(image) );
        LogoSearch.setIcon(new ImageIcon(image) );
        jLabelLogo.setIcon(new ImageIcon(image) );
        LogoView.setIcon(new ImageIcon(image) );
        
        ImageIcon home = new ImageIcon(getClass().getResource("home.jpg")); 
        Image img = home.getImage().getScaledInstance(51, 57, Image.SCALE_SMOOTH);
        jLabelHome.setIcon(new ImageIcon(img) );
        jLabelHome1.setIcon(new ImageIcon(img) );
        jLabelHome2.setIcon(new ImageIcon(img) );
        jLabelHome3.setIcon(new ImageIcon(img) );
        jLabelHome4.setIcon(new ImageIcon(img) );
        
        
        TableColumnModel tcm = tblRecords.getColumnModel();
        tcm.getColumn(0).setPreferredWidth(20);
        tcm.getColumn(1).setPreferredWidth(120);
        tcm.getColumn(2).setPreferredWidth(30);
        tcm.getColumn(3).setPreferredWidth(5);
        tcm.getColumn(4).setPreferredWidth(50);
        tcm.getColumn(5).setPreferredWidth(150);
        tcm.getColumn(6).setPreferredWidth(50);
        tcm.getColumn(7).setPreferredWidth(30);
        tcm.getColumn(8).setPreferredWidth(30);
        tcm.getColumn(9).setPreferredWidth(20);
        tcm.getColumn(10).setPreferredWidth(10);
        tcm.getColumn(11).setPreferredWidth(10);
        
        
        //for displaying data from table in Mysql
        DefaultTableModel model = (DefaultTableModel) tblRecords.getModel();
        model.setRowCount(0);
        
        InPatient2 pr = new InPatient2();
        ResultSet res = null;
        try{
            res = pr.getAll();
            res.beforeFirst();
            while(res.next()){
                model.addRow(new Object[]{Integer.parseInt(res.getString(1)),res.getString(2),res.getString(3),Integer.parseInt(res.getString(4)),res.getString(5),res.getString(6),res.getString(7),res.getString(8),res.getString(9),res.getString(10),res.getString(11),res.getString(12)});
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Cannot display" + e.toString());
        }
        
        
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        txtAge = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtDisease = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtSOD = new javax.swing.JTextField();
        txtCheckin = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtRoomn = new javax.swing.JTextField();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel15 = new javax.swing.JLabel();
        rdoPrivate = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        rdoWard = new javax.swing.JRadioButton();
        cmbGender = new javax.swing.JComboBox();
        cmbBuilding = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelHome = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        LogoAdd = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnAddClinical = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabelHome1 = new javax.swing.JLabel();
        LogoUpdate = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtName1 = new javax.swing.JTextField();
        txtAge1 = new javax.swing.JTextField();
        txtPhone1 = new javax.swing.JTextField();
        txtAddress1 = new javax.swing.JTextField();
        txtDisease1 = new javax.swing.JTextField();
        txtSOD1 = new javax.swing.JTextField();
        txtCheckin1 = new javax.swing.JTextField();
        txtRoomn1 = new javax.swing.JTextField();
        cmboGender = new javax.swing.JComboBox();
        jPanel10 = new javax.swing.JPanel();
        rdoWard1 = new javax.swing.JRadioButton();
        rdoPrivate1 = new javax.swing.JRadioButton();
        cmboBuilding = new javax.swing.JComboBox();
        jPanel11 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDisplay = new javax.swing.JTextArea();
        btnPrint = new javax.swing.JButton();
        btnClear1 = new javax.swing.JButton();
        txtSearch1 = new javax.swing.JTextField();
        btnSearch1 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        btnClinicalData = new javax.swing.JButton();
        btnPrescription = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        LogoSearch = new javax.swing.JLabel();
        jLabelHome2 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        btnPrescription1 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelHome3 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        txtSearch2 = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnSearch2 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        txtName2 = new javax.swing.JTextField();
        txtAge2 = new javax.swing.JTextField();
        txtPhone2 = new javax.swing.JTextField();
        txtAddress2 = new javax.swing.JTextField();
        txtDisease2 = new javax.swing.JTextField();
        txtSOD2 = new javax.swing.JTextField();
        txtDate2 = new javax.swing.JTextField();
        txtRoomn2 = new javax.swing.JTextField();
        cmboGender1 = new javax.swing.JComboBox();
        jPanel20 = new javax.swing.JPanel();
        rdoWard2 = new javax.swing.JRadioButton();
        rdoPrivate2 = new javax.swing.JRadioButton();
        cmboBuilding1 = new javax.swing.JComboBox();
        jPanel21 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRecords = new javax.swing.JTable();
        jPanel15 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        LogoView = new javax.swing.JLabel();
        jLabelHome4 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAge.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        jPanel4.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 210, 30));

        btnClear.setBackground(new java.awt.Color(0, 153, 153));
        btnClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel4.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 520, 90, 30));

        btnAdd.setBackground(new java.awt.Color(0, 153, 153));
        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("ADD");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel4.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 520, 90, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("Age:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Phone:");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("Gender:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Full Name:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 90, 20));

        txtName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel4.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 210, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 153));
        jLabel8.setText("Address:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 153));
        jLabel9.setText("Disease:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, -1, 20));
        jPanel4.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 210, 40));
        jPanel4.add(txtDisease, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 190, 210, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 153));
        jLabel10.setText("StatusOfDisease:");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 153));
        jLabel11.setText("Admission Date:");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 153));
        jLabel13.setText("RoomNo.:");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 153));
        jLabel14.setText("Building:");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, -1, -1));

        txtSOD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSODActionPerformed(evt);
            }
        });
        jPanel4.add(txtSOD, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 240, 210, 30));

        txtCheckin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCheckinActionPerformed(evt);
            }
        });
        jPanel4.add(txtCheckin, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 290, 210, 30));
        jPanel4.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 210, 30));

        txtRoomn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoomnActionPerformed(evt);
            }
        });
        jPanel4.add(txtRoomn, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 340, 210, 30));

        jToolBar1.setRollover(true);
        jPanel4.add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 570, 0, 10));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 153));
        jLabel15.setText("RoomType:");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 450, -1, 20));

        rdoPrivate.setBackground(new java.awt.Color(0, 255, 102));
        buttonGroup1.add(rdoPrivate);
        rdoPrivate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdoPrivate.setForeground(new java.awt.Color(0, 102, 102));
        rdoPrivate.setText("Private");
        rdoPrivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoPrivateActionPerformed(evt);
            }
        });
        jPanel4.add(rdoPrivate, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 460, 80, -1));

        jPanel5.setBackground(new java.awt.Color(0, 255, 102));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rdoWard.setBackground(new java.awt.Color(0, 255, 102));
        buttonGroup1.add(rdoWard);
        rdoWard.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdoWard.setForeground(new java.awt.Color(0, 102, 102));
        rdoWard.setText("Ward");
        rdoWard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoWardActionPerformed(evt);
            }
        });
        jPanel5.add(rdoWard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, -1));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 450, 210, 40));

        cmbGender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbGender.setForeground(new java.awt.Color(0, 153, 153));
        cmbGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Gender...", "Male", "Female" }));
        cmbGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGenderActionPerformed(evt);
            }
        });
        jPanel4.add(cmbGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 210, 30));

        cmbBuilding.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbBuilding.setForeground(new java.awt.Color(0, 153, 153));
        cmbBuilding.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Building...", "A", "B", "C" }));
        cmbBuilding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBuildingActionPerformed(evt);
            }
        });
        jPanel4.add(cmbBuilding, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 390, 210, 30));

        jPanel6.setBackground(new java.awt.Color(0, 204, 204));
        jPanel6.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Add Patient");
        jPanel6.add(jLabel2);
        jLabel2.setBounds(140, 20, 200, 52);
        jPanel6.add(jSeparator2);
        jSeparator2.setBounds(0, -22, 1080, 2);

        jLabelHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PatientsInfo/home.jpg"))); // NOI18N
        jLabelHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHomeMouseClicked(evt);
            }
        });
        jPanel6.add(jLabelHome);
        jLabelHome.setBounds(1230, 10, 70, 60);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Home");
        jPanel6.add(jLabel16);
        jLabel16.setBounds(1230, 70, 60, 14);

        LogoAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PatientsInfo/bd.jpg"))); // NOI18N
        jPanel6.add(LogoAdd);
        LogoAdd.setBounds(0, 0, 150, 90);

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 90));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -18, -1, 20));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PatientsInfo/patient.png"))); // NOI18N
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 220, 210, 200));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), null));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 210, 230, 220));

        btnAddClinical.setBackground(new java.awt.Color(0, 153, 153));
        btnAddClinical.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddClinical.setForeground(new java.awt.Color(255, 255, 255));
        btnAddClinical.setText("ADD CLINICAL DATA");
        btnAddClinical.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddClinicalMouseClicked(evt);
            }
        });
        btnAddClinical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddClinicalActionPerformed(evt);
            }
        });
        jPanel4.add(btnAddClinical, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, 190, 30));

        jTabbedPane1.addTab("Add Patient", jPanel4);

        jPanel8.setBackground(new java.awt.Color(204, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(0, 204, 204));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Update Patient");
        jPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Home");
        jPanel9.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 70, -1, -1));

        jLabelHome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PatientsInfo/home.jpg"))); // NOI18N
        jLabelHome1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelHome1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHome1MouseClicked(evt);
            }
        });
        jPanel9.add(jLabelHome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 10, 90, 60));

        LogoUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PatientsInfo/bd.jpg"))); // NOI18N
        jPanel9.add(LogoUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 90));

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1581, 90));

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchMouseClicked(evt);
            }
        });
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        jPanel8.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 170, 30));

        btnUpdate.setBackground(new java.awt.Color(0, 153, 153));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel8.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 130, 100, 30));

        btnSearch.setBackground(new java.awt.Color(0, 153, 153));
        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel8.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 100, 30));

        jSeparator3.setForeground(new java.awt.Color(0, 204, 204));
        jPanel8.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 1450, 40));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 153, 153));
        jLabel17.setText("RoomType:");
        jPanel8.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 510, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 153, 153));
        jLabel18.setText("Patient ID");
        jPanel8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 153, 153));
        jLabel19.setText("Full Name:");
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 153, 153));
        jLabel20.setText("Gender:");
        jPanel8.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 153, 153));
        jLabel21.setText("Age:");
        jPanel8.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 153, 153));
        jLabel22.setText("Phone:");
        jPanel8.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 153, 153));
        jLabel23.setText("Address:");
        jPanel8.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 580, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 153, 153));
        jLabel24.setText("Disease:");
        jPanel8.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 153, 153));
        jLabel25.setText("StatusOfDisease:");
        jPanel8.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 153, 153));
        jLabel26.setText("AdmissionDate:");
        jPanel8.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 153, 153));
        jLabel27.setText("RoomNo:");
        jPanel8.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 153, 153));
        jLabel28.setText("Building:");
        jPanel8.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, -1, -1));
        jPanel8.add(txtName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 220, 30));
        jPanel8.add(txtAge1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 220, 30));
        jPanel8.add(txtPhone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 220, 30));
        jPanel8.add(txtAddress1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 580, 720, 40));
        jPanel8.add(txtDisease1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 270, 240, 30));
        jPanel8.add(txtSOD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, 240, 30));

        txtCheckin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCheckin1ActionPerformed(evt);
            }
        });
        jPanel8.add(txtCheckin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 220, 30));
        jPanel8.add(txtRoomn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, 240, 30));

        cmboGender.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cmboGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Gender...", "Male", "Female" }));
        jPanel8.add(cmboGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 220, 30));

        jPanel10.setBackground(new java.awt.Color(51, 255, 102));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rdoWard1.setBackground(new java.awt.Color(51, 255, 102));
        buttonGroup1.add(rdoWard1);
        rdoWard1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdoWard1.setForeground(new java.awt.Color(0, 153, 153));
        rdoWard1.setText("Ward");
        jPanel10.add(rdoWard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 8, -1, -1));

        rdoPrivate1.setBackground(new java.awt.Color(51, 255, 102));
        buttonGroup1.add(rdoPrivate1);
        rdoPrivate1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdoPrivate1.setForeground(new java.awt.Color(0, 153, 153));
        rdoPrivate1.setText("Private");
        jPanel10.add(rdoPrivate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 8, -1, -1));

        jPanel8.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 510, 240, 40));

        cmboBuilding.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmboBuilding.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Building...", "A", "B", "C" }));
        jPanel8.add(cmboBuilding, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 450, 240, 30));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), new java.awt.Color(0, 204, 204)));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PatientsInfo/user1.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addContainerGap())
        );

        jPanel8.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 230, 220, 210));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 1450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 170, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Update Patient", jPanel1);

        jPanel12.setBackground(new java.awt.Color(204, 255, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDisplay.setColumns(20);
        txtDisplay.setRows(5);
        jScrollPane2.setViewportView(txtDisplay);

        jPanel12.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 110, 580, 560));

        btnPrint.setBackground(new java.awt.Color(0, 153, 153));
        btnPrint.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(255, 255, 255));
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel12.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 550, 110, 40));

        btnClear1.setBackground(new java.awt.Color(0, 153, 153));
        btnClear1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnClear1.setForeground(new java.awt.Color(255, 255, 255));
        btnClear1.setText("Clear");
        btnClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear1ActionPerformed(evt);
            }
        });
        jPanel12.add(btnClear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 550, 110, 40));
        jPanel12.add(txtSearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 160, 30));

        btnSearch1.setBackground(new java.awt.Color(0, 153, 153));
        btnSearch1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnSearch1.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch1.setText("Search");
        btnSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch1ActionPerformed(evt);
            }
        });
        jPanel12.add(btnSearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 100, 30));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 153, 153));
        jLabel31.setText("Patients Profile");
        jPanel12.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 160, 20));

        btnClinicalData.setBackground(new java.awt.Color(0, 153, 153));
        btnClinicalData.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnClinicalData.setForeground(new java.awt.Color(255, 255, 255));
        btnClinicalData.setText("CLINICAL DATA");
        btnClinicalData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClinicalDataActionPerformed(evt);
            }
        });
        jPanel12.add(btnClinicalData, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 270, 40));

        btnPrescription.setBackground(new java.awt.Color(0, 153, 153));
        btnPrescription.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnPrescription.setForeground(new java.awt.Color(255, 255, 255));
        btnPrescription.setText("LABORATORIES");
        jPanel12.add(btnPrescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 270, 40));

        jPanel16.setBackground(new java.awt.Color(0, 204, 204));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Search Patient");
        jPanel16.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, 40));

        LogoSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PatientsInfo/bd.jpg"))); // NOI18N
        jPanel16.add(LogoSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 90));

        jLabelHome2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PatientsInfo/home.jpg"))); // NOI18N
        jLabelHome2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelHome2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHome2MouseClicked(evt);
            }
        });
        jPanel16.add(jLabelHome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 10, 90, 60));

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("Home");
        jPanel16.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 70, -1, -1));

        jPanel12.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 90));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), new java.awt.Color(0, 204, 204)));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PatientsInfo/user1.jpg"))); // NOI18N
        jPanel17.add(jLabel33);

        jPanel12.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 250, 220));

        btnPrescription1.setBackground(new java.awt.Color(0, 153, 153));
        btnPrescription1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnPrescription1.setForeground(new java.awt.Color(255, 255, 255));
        btnPrescription1.setText("PRESCRIPTION");
        btnPrescription1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrescription1ActionPerformed(evt);
            }
        });
        jPanel12.add(btnPrescription1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 270, 40));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 153, 153));
        jLabel34.setText("Input Patient's ID");
        jPanel12.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 160, 20));

        jTabbedPane1.addTab("Search Patient", jPanel12);

        jPanel18.setBackground(new java.awt.Color(204, 255, 255));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel19.setBackground(new java.awt.Color(0, 204, 204));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Delete Patient");
        jPanel19.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PatientsInfo/bd.jpg"))); // NOI18N
        jPanel19.add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 90));

        jLabelHome3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PatientsInfo/home.jpg"))); // NOI18N
        jLabelHome3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelHome3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHome3MouseClicked(evt);
            }
        });
        jPanel19.add(jLabelHome3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 10, 90, 60));

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Home");
        jPanel19.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 70, -1, -1));

        jPanel18.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1581, 90));

        txtSearch2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSearch2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSearch2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearch2MouseClicked(evt);
            }
        });
        txtSearch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearch2ActionPerformed(evt);
            }
        });
        jPanel18.add(txtSearch2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 170, 30));

        btnDelete.setBackground(new java.awt.Color(0, 153, 153));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel18.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 130, 100, 30));

        btnSearch2.setBackground(new java.awt.Color(0, 153, 153));
        btnSearch2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearch2.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch2.setText("Search");
        btnSearch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch2ActionPerformed(evt);
            }
        });
        jPanel18.add(btnSearch2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 100, 30));

        jSeparator4.setForeground(new java.awt.Color(0, 204, 204));
        jPanel18.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 1450, 40));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 153, 153));
        jLabel36.setText("RoomType:");
        jPanel18.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 510, -1, -1));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 153, 153));
        jLabel37.setText("Patient ID");
        jPanel18.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, -1, -1));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 153, 153));
        jLabel38.setText("Full Name:");
        jPanel18.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 153, 153));
        jLabel39.setText("Gender:");
        jPanel18.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, -1));

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 153, 153));
        jLabel40.setText("Age:");
        jPanel18.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, -1, -1));

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 153, 153));
        jLabel41.setText("Phone:");
        jPanel18.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, -1, -1));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 153, 153));
        jLabel42.setText("Address:");
        jPanel18.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 580, -1, -1));

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 153, 153));
        jLabel43.setText("Disease:");
        jPanel18.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, -1, -1));

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 153, 153));
        jLabel44.setText("StatusOfDisease:");
        jPanel18.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, -1, -1));

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 153, 153));
        jLabel45.setText("AdmissionDate:");
        jPanel18.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, -1, -1));

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 153, 153));
        jLabel46.setText("RoomNo:");
        jPanel18.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, -1, -1));

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(0, 153, 153));
        jLabel47.setText("Building:");
        jPanel18.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, -1, -1));
        jPanel18.add(txtName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 220, 30));
        jPanel18.add(txtAge2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 220, 30));
        jPanel18.add(txtPhone2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 220, 30));
        jPanel18.add(txtAddress2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 580, 720, 40));
        jPanel18.add(txtDisease2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 270, 240, 30));
        jPanel18.add(txtSOD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, 240, 30));

        txtDate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDate2ActionPerformed(evt);
            }
        });
        jPanel18.add(txtDate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 220, 30));
        jPanel18.add(txtRoomn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, 240, 30));

        cmboGender1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cmboGender1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Gender...", "Male", "Female" }));
        jPanel18.add(cmboGender1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 220, 30));

        jPanel20.setBackground(new java.awt.Color(51, 255, 102));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rdoWard2.setBackground(new java.awt.Color(51, 255, 102));
        buttonGroup1.add(rdoWard2);
        rdoWard2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdoWard2.setForeground(new java.awt.Color(0, 153, 153));
        rdoWard2.setText("Ward");
        jPanel20.add(rdoWard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 8, -1, -1));

        rdoPrivate2.setBackground(new java.awt.Color(51, 255, 102));
        buttonGroup1.add(rdoPrivate2);
        rdoPrivate2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdoPrivate2.setForeground(new java.awt.Color(0, 153, 153));
        rdoPrivate2.setText("Private");
        jPanel20.add(rdoPrivate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 8, -1, -1));

        jPanel18.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 510, 240, 40));

        cmboBuilding1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmboBuilding1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Building...", "A", "B", "C" }));
        jPanel18.add(cmboBuilding1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 450, 240, 30));

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), new java.awt.Color(0, 204, 204)));

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PatientsInfo/user1.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel48)
                .addContainerGap())
        );

        jPanel18.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 230, 220, 210));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 1450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 130, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Delete Patient", jPanel2);

        jPanel14.setBackground(new java.awt.Color(204, 255, 255));
        jPanel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel14MousePressed(evt);
            }
        });
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblRecords.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient Id", "FullName", "Gender", "Age", "Phone", "Address", "Disease", "Status", "AdmissionDate", "Room Type", "Room Number", "Building"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblRecords.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblRecordsMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblRecords);

        jPanel14.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 1240, 490));

        jPanel15.setBackground(new java.awt.Color(0, 204, 204));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Patients Records");
        jPanel15.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        LogoView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PatientsInfo/bd.jpg"))); // NOI18N
        jPanel15.add(LogoView, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 90));

        jLabelHome4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PatientsInfo/home.jpg"))); // NOI18N
        jLabelHome4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelHome4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHome4MouseClicked(evt);
            }
        });
        jPanel15.add(jLabelHome4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 10, 90, 60));

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("Home");
        jPanel15.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 70, -1, -1));

        jPanel14.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1530, 90));

        jTabbedPane1.addTab("View Patients", jPanel14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        
        txtName.setText("");
        cmbGender.getName();
        txtAge.setText("");
        txtPhone.setText("");
        txtAddress.setText("");
        txtDisease.setText("");
        txtSOD.setText("");
        txtCheckin.setText("");
        txtRoomn.setText("");
        cmbGender.getModel().setSelectedItem("Select Gender");
        cmbBuilding.getModel().setSelectedItem("Select Building");
        buttonGroup1.clearSelection();

    }//GEN-LAST:event_btnClearActionPerformed

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:

        
        String name = txtName.getText();

        String gender = "";
        if(cmbGender.getSelectedItem().equals("Male")){
            gender = "Male";
        }
        if(cmbGender.getSelectedItem().equals("Female")){
            gender = "Female";
        }

        String age = txtAge.getText();
        String phone = txtPhone.getText();
        String address = txtAddress.getText();
        String disease = txtDisease.getText();
        String status = txtSOD.getText();
        String checkin = txtCheckin.getText();
        String roomn = "";
        if(rdoWard.isSelected()){
            roomn="Ward";
        }
        if(rdoPrivate.isSelected()){
            roomn="Private";
        }

        String roomt = txtRoomn.getText();

        String building = "";
        if(cmbBuilding.getSelectedItem().equals("A")){
            building = "A";
        }
        if(cmbBuilding.getSelectedItem().equals("B")){
            building = "B";
        }
        if(cmbBuilding.getSelectedItem().equals("C")){
            building = "C";
        }

        InPatient2 reg = new InPatient2(name,gender,age,phone,address,disease,status,checkin,roomt,roomn,building);
//        if(id.isEmpty()){
//            JOptionPane.showMessageDialog(null,"Please enter patient id");
//        }
//        else if (checkId(id)) {
//            JOptionPane.showMessageDialog(null, "Patient ID already exist!\n Please try another one.");
//        }
        if(name.isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter patient name");
        }
        else if(gender.equals("Select Gender...")){
            JOptionPane.showMessageDialog(null,"Please select patient gender");
        }
        else if(age.isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter patient age");
        }
        else if(phone.isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter patient phone number");
        }
        else if(address.isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter patient address");
        }
        else if(disease.isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter patient disease");
        }
        else if(status.isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter the status of the diseasse");
        }
        else if(checkin.isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter the date checked in");
        }
        else if(roomn.isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter the room number");
        }
        else if(building.isEmpty()){
            JOptionPane.showMessageDialog(null,"Please select building");
        }
        else if(reg.addNew())
        JOptionPane.showMessageDialog(null,"New Patient added!");
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtSODActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSODActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSODActionPerformed

    private void txtCheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCheckinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCheckinActionPerformed

    private void txtRoomnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoomnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoomnActionPerformed

    private void rdoPrivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoPrivateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoPrivateActionPerformed

    private void rdoWardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoWardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoWardActionPerformed

    private void cmbGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGenderActionPerformed

    private void cmbBuildingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBuildingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBuildingActionPerformed

    private void jLabelHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHomeMouseClicked
        // TODO add your handling code here:
        ReceptionistModule rm = new ReceptionistModule();
        rm.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelHomeMouseClicked

    private void btnAddClinicalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddClinicalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddClinicalMouseClicked

    private void btnAddClinicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddClinicalActionPerformed
        // TODO add your handling code here:
        new ClinicalDataR().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAddClinicalActionPerformed

    private void jLabelHome1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHome1MouseClicked
        // TODO add your handling code here:
        ReceptionistModule rm = new ReceptionistModule();
        rm.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelHome1MouseClicked

    private void txtSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchMouseClicked

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String id = txtSearch.getText();
        String name = txtName1.getText();

        String gender = "";
        if(cmboGender.getSelectedItem().equals("Male")){
            gender = "Male";
        }
        if(cmboGender.getSelectedItem().equals("Female")){
            gender = "Female";
        }
        String age = txtAge1.getText();
        String phone = txtPhone1.getText();
        String address = txtAddress1.getText();
        String disease = txtDisease1.getText();
        String status = txtSOD1.getText();
        String checkin = txtCheckin1.getText();
        String roomt = "";
        if(rdoWard1.isSelected()){
            roomt="Ward";
        }
        if(rdoPrivate1.isSelected()){
            roomt="Private";
        }

        String roomn = txtRoomn1.getText();
        String building = "";
        if(cmboBuilding.getSelectedItem().equals("A")){
            building = "A";
        }
        if(cmboBuilding.getSelectedItem().equals("B")){
            building = "B";
        }
        if(cmboBuilding.getSelectedItem().equals("C")){
            building = "C";
        }

        InPatient2 reg = new InPatient2();
        if(reg.updateInfo(id,name,gender,age,phone,address,disease,status,checkin,roomt,roomn,building)){
            JOptionPane.showMessageDialog(null,"Successfully updated the record!");
        }

        txtSearch.setText("");
        txtName1.setText("");
        cmboGender.getName();
        txtAge1.setText("");
        txtPhone1.setText("");
        txtAddress1.setText("");
        txtDisease1.setText("");
        txtSOD1.setText("");
        txtCheckin1.setText("");
        txtRoomn1.setText("");
        cmboGender.getModel().setSelectedItem("Select Gender");
        cmboBuilding.getModel().setSelectedItem("Select Building");
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String id = txtSearch.getText();
        InPatient2 ad = new InPatient2();
        ResultSet res = ad.getInfo(id);

        try {
            res.beforeFirst();
            while(res.next()){
                txtSearch.setText(res.getString("PatientId"));
                txtName1.setText(res.getString("FullName"));

                String gender = res.getString("Gender");
                if(gender.equals("Male")){
                    cmboGender.getModel().setSelectedItem("Male");
                }
                else if(gender.equals("Female")){
                    cmboGender.getModel().setSelectedItem("Female");
                }

                txtAge1.setText(res.getString("Age"));
                txtPhone1.setText(res.getString("Phone"));
                txtAddress1.setText(res.getString("Address"));
                txtDisease1.setText(res.getString("Disease"));
                txtSOD1.setText(res.getString("StatusOfDisease"));
                txtCheckin1.setText(res.getString("CheckIn"));

                String room=res.getString("RoomType");
                if(room.equals("Ward")){
                    rdoWard1.setSelected(true);
                }
                else if(room.equals("Private")){
                    rdoPrivate1.setSelected(true);
                }

                txtRoomn1.setText(res.getString("RoomNo"));

                String building = res.getString("Building");
                if(building.equals("A")){
                    cmboBuilding.getModel().setSelectedItem("A");
                }
                if(building.equals("B")){
                    cmboBuilding.getModel().setSelectedItem("B");
                }
                else if(building.equals("C")){
                    cmboBuilding.getModel().setSelectedItem("C");
                }
            }

            while(res.next()){
                txtSearch.setText(res.getString(""));
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Id does not exist!");
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtCheckin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCheckin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCheckin1ActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        try{
            txtDisplay.print();
        }catch (PrinterException ex){
            Logger.getLogger(InPatientR.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear1ActionPerformed
        // TODO add your handling code here:
        txtDisplay.setText("");
        txtSearch1.setText("");
    }//GEN-LAST:event_btnClear1ActionPerformed

    private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed
        // TODO add your handling code here:
        String id = txtSearch1.getText();
        InPatient2 reg = new InPatient2();
        ResultSet res = reg.getInfo(id);

        try{
            res.beforeFirst();
            while(res.next()){
                String pid = res.getString("PatientId");
                String name = res.getString("FullName");
                String gender = res.getString("Gender");
                String age = res.getString("Age");
                String phone = res.getString("Phone");
                String address = res.getString("Address");
                String disease = res.getString("Disease");
                String status = res.getString("StatusOfDisease");
                String checkin = res.getString("Checkin");
                String roomt = res.getString("RoomType");
                String roomn = res.getString("RoomNo");
                String building = res.getString("Building");

                txtDisplay.append("\n\t\tPatients Information\n\n\n"
                    +"\n\t Patient ID: \t\t" + pid
                    +"\n\t Name: \t\t" + name
                    +"\n\t Age: \t\t" +age
                    +"\n\t Gender: \t\t" + gender
                    +"\n\t Phone: \t\t" + phone
                    +"\n\t Address: \t\t" + address
                    +"\n\t Disease: \t\t" + disease
                    +"\n\t StatusOfDisease: \t" + status
                    +"\n\t AdmissionDate: \t" + checkin
                    +"\n\t Room No: \t\t" + roomn
                    +"\n\t Building: \t\t" + building
                    +"\n\t Room Type: \t\t" + roomt
                    +"\n\n\n\n\t\n\t\n\t"
                    +" Click CLINICAL DATA for Patients Vital Sign\n"
                    + "\t Click Prescription for Physicians Prescriptions.");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Id does not exist!");
        }
    }//GEN-LAST:event_btnSearch1ActionPerformed

    private void btnClinicalDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClinicalDataActionPerformed
        // TODO add your handling code here:
        ClinicalDataR cr = new ClinicalDataR();
        cr.setVisible(true);
        dispose();
       
    }//GEN-LAST:event_btnClinicalDataActionPerformed

    private void jLabelHome2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHome2MouseClicked
        // TODO add your handling code here:
        new ReceptionistModule().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelHome2MouseClicked

    private void btnPrescription1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrescription1ActionPerformed
        // TODO add your handling code here:
        new PrescriptionR().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btnPrescription1ActionPerformed

    private void jLabelHome3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHome3MouseClicked
        // TODO add your handling code here:
        new ReceptionistModule().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelHome3MouseClicked

    private void txtSearch2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearch2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearch2MouseClicked

    private void txtSearch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearch2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearch2ActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String id = txtSearch2.getText();
        InPatient2 reg = new InPatient2();
        int p = JOptionPane.showConfirmDialog(null,"Are you sure you want to delete patient?","Hospital Management System",JOptionPane.YES_NO_OPTION);
        if(p==0){
            reg.deleteRecord(id);
            JOptionPane.showMessageDialog(null, "Successfully deleted!");
        }

        txtSearch2.setText("");
        txtName2.setText("");
        txtAge2.setText("");
        txtPhone2.setText("");
        txtAddress2.setText("");
        txtDisease2.setText("");
        txtSOD2.setText("");
        txtDate2.setText("");
        txtRoomn2.setText("");
        cmboGender1.getModel().setSelectedItem("Select Gender");
        cmboBuilding1.getModel().setSelectedItem("Select Building");
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSearch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch2ActionPerformed
        // TODO add your handling code here:
        String id = txtSearch2.getText();
        InPatient2 ad = new InPatient2();
        ResultSet res = ad.getInfo(id);

        try {
            res.beforeFirst();
            while(res.next()){
                txtSearch2.setText(res.getString("PatientId"));
                txtName2.setText(res.getString("FullName"));

                String gender = res.getString("Gender");
                if(gender.equals("Male")){
                    cmboGender1.getModel().setSelectedItem("Male");
                }
                else if(gender.equals("Female")){
                    cmboGender1.getModel().setSelectedItem("Female");
                }

                txtAge2.setText(res.getString("Age"));
                txtPhone2.setText(res.getString("Phone"));
                txtAddress2.setText(res.getString("Address"));
                txtDisease2.setText(res.getString("Disease"));
                txtSOD2.setText(res.getString("StatusOfDisease"));
                txtDate2.setText(res.getString("CheckIn"));

                String room=res.getString("RoomType");
                if(room.equals("Ward")){
                    rdoWard2.setSelected(true);
                }
                else if(room.equals("Private")){
                    rdoPrivate2.setSelected(true);
                }

                txtRoomn2.setText(res.getString("RoomNo"));

                String building = res.getString("Building");
                if(building.equals("A")){
                    cmboBuilding1.getModel().setSelectedItem("A");
                }
                if(building.equals("B")){
                    cmboBuilding1.getModel().setSelectedItem("B");
                }
                else if(building.equals("C")){
                    cmboBuilding1.getModel().setSelectedItem("C");
                }
            }

            while(res.next()){
                txtSearch2.setText(res.getString(""));
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Id does not exist!");
        }
    }//GEN-LAST:event_btnSearch2ActionPerformed

    private void txtDate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDate2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDate2ActionPerformed

    private void tblRecordsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRecordsMousePressed
        // code for clearing table
        /*DefaultTableModel model = (DefaultTableModel) tblRecords.getModel();
        model.setRowCount(0);*/
    }//GEN-LAST:event_tblRecordsMousePressed

    private void jLabelHome4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHome4MouseClicked
        // TODO add your handling code here:
        new ReceptionistModule().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelHome4MouseClicked

    private void jPanel14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel14MousePressed

    //function to check if Patient Id already exist
    public boolean checkId(String pid) {
        PreparedStatement ps;
        ResultSet rs;
        boolean checkuser = false;

        String query = "SELECT * FROM `registration` WHERE `PatientId` =?";

        try {
            ps = MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, pid);

            rs = ps.executeQuery();

            if (rs.next()) {
                checkuser = true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
        return checkuser;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InPatientR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InPatientR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InPatientR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InPatientR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InPatientR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogoAdd;
    private javax.swing.JLabel LogoSearch;
    private javax.swing.JLabel LogoUpdate;
    private javax.swing.JLabel LogoView;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddClinical;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClear1;
    private javax.swing.JButton btnClinicalData;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnPrescription;
    private javax.swing.JButton btnPrescription1;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearch1;
    private javax.swing.JButton btnSearch2;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbBuilding;
    private javax.swing.JComboBox cmbGender;
    private javax.swing.JComboBox cmboBuilding;
    private javax.swing.JComboBox cmboBuilding1;
    private javax.swing.JComboBox cmboGender;
    private javax.swing.JComboBox cmboGender1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelHome;
    private javax.swing.JLabel jLabelHome1;
    private javax.swing.JLabel jLabelHome2;
    private javax.swing.JLabel jLabelHome3;
    private javax.swing.JLabel jLabelHome4;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JRadioButton rdoPrivate;
    private javax.swing.JRadioButton rdoPrivate1;
    private javax.swing.JRadioButton rdoPrivate2;
    private javax.swing.JRadioButton rdoWard;
    private javax.swing.JRadioButton rdoWard1;
    private javax.swing.JRadioButton rdoWard2;
    private javax.swing.JTable tblRecords;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAddress1;
    private javax.swing.JTextField txtAddress2;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAge1;
    private javax.swing.JTextField txtAge2;
    private javax.swing.JTextField txtCheckin;
    private javax.swing.JTextField txtCheckin1;
    private javax.swing.JTextField txtDate2;
    private javax.swing.JTextField txtDisease;
    private javax.swing.JTextField txtDisease1;
    private javax.swing.JTextField txtDisease2;
    private javax.swing.JTextArea txtDisplay;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtName1;
    private javax.swing.JTextField txtName2;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPhone1;
    private javax.swing.JTextField txtPhone2;
    private javax.swing.JTextField txtRoomn;
    private javax.swing.JTextField txtRoomn1;
    private javax.swing.JTextField txtRoomn2;
    private javax.swing.JTextField txtSOD;
    private javax.swing.JTextField txtSOD1;
    private javax.swing.JTextField txtSOD2;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSearch1;
    private javax.swing.JTextField txtSearch2;
    // End of variables declaration//GEN-END:variables
}
