/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ReceptionistPortal;

import Login.MyConnection;
import PatientsInfo.InPatient2;
import PatientsInfo.Prescription2;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author kli ann
 */
public class PatientPrescriptionR extends javax.swing.JFrame {

    /**
     * Creates new form PatientPrescriptionR
     */
    public PatientPrescriptionR() {
        initComponents();
        
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        showDate();
        showTime();
    }
    
    void showDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
        date.setText(s.format(d));
    }
    void showTime() {
        new Timer(0, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                time.setText(s.format(d));
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmboIllness = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMedicine = new javax.swing.JTextField();
        txtDosage = new javax.swing.JTextField();
        txtDailyDose = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtStorage = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPhysician = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtPname = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtSex = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        physicianlbl = new javax.swing.JLabel();
        namelbl = new javax.swing.JLabel();
        medicinelbl = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        IDlbl = new javax.swing.JLabel();
        addresslbl = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        agelbl = new javax.swing.JLabel();
        dosagelbl = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        daAlbl = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        storagelbl = new javax.swing.JLabel();
        dailydoselbl = new javax.swing.JLabel();
        precautionlbl = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        illnesslbl = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        sexlbl = new javax.swing.JLabel();
        licenselbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPrecautions = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDosandAdmin = new javax.swing.JTextArea();
        btnAdd = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDisplay = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Patients Prescription");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PatientsInfo/prescription.png"))); // NOI18N
        jLabel2.setText("Name of Tablets:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 110, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 79));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Administration:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));

        cmboIllness.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmboIllness.setForeground(new java.awt.Color(255, 255, 255));
        cmboIllness.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "......", "Colds", "Cough", "Fever", "Diarrhea", "HB Pressure", "Iron Defficiency" }));
        cmboIllness.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmboIllnessActionPerformed(evt);
            }
        });
        jPanel1.add(cmboIllness, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 200, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Daily Dose:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("Dosage (mg):");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("Medicine:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jLabel7.setText("Dosage and ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 153));
        jLabel8.setText("Illness:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, 20));
        jPanel1.add(txtMedicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 200, 30));
        jPanel1.add(txtDosage, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 200, 30));
        jPanel1.add(txtDailyDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 200, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 153));
        jLabel9.setText("Precautions:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 153));
        jLabel10.setText("Storage:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));
        jPanel1.add(txtStorage, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 200, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 153));
        jLabel11.setText("Patient ID:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, -1, -1));
        jPanel1.add(txtPhysician, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 210, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 153));
        jLabel12.setText("Patient Name:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, -1, -1));
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 130, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 153));
        jLabel13.setText("Patient Age:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, -1, -1));
        jPanel1.add(txtPname, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, 210, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 153));
        jLabel14.setText("Sex:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, -1, -1));
        jPanel1.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 210, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 153));
        jLabel15.setText("Patient Address:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, -1, 20));

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        jPanel1.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, 570, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 153));
        jLabel16.setText("Physician:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, -1, 20));
        jPanel1.add(txtSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, 210, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel17.setText("DOCTOR PRESCRIPTION");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 120, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Tabunok, Talisay City, Cebu");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 150, -1, 20));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel19.setText("Mobile No.: 09196459422");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 170, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 210, 530, 3));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PatientsInfo/presc.png"))); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 120, -1, 60));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Time:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 190, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Date:");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 190, -1, -1));
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 190, -1, -1));
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 190, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Sex:");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 220, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("Name:");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 220, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("Medicine:");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 350, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setText("Age:");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 220, -1, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 240, 80, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 240, 240, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 242, 50, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 270, 430, 10));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setText("License #:");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 630, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setText("Physician:");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 610, -1, -1));

        physicianlbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(physicianlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 610, -1, -1));
        jPanel1.add(namelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 220, -1, -1));
        jPanel1.add(medicinelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 350, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setText("PID:");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 190, -1, -1));

        IDlbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(IDlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 190, 60, -1));
        jPanel1.add(addresslbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 250, -1, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel32.setText("Address:");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 250, -1, -1));
        jPanel1.add(agelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 220, -1, 20));
        jPanel1.add(dosagelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 390, -1, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setText("Dosage:");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 390, -1, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 185, 80, 22));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel34.setText("Dosage and Administration:");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 430, -1, -1));
        jPanel1.add(daAlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 430, -1, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel33.setText("Daily Dose");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 320, -1, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel35.setText("Storage:");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 350, -1, -1));
        jPanel1.add(storagelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 360, 190, 20));
        jPanel1.add(dailydoselbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 330, 190, 20));
        jPanel1.add(precautionlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 480, -1, -1));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel37.setText("Precaution:");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 480, -1, -1));
        jPanel1.add(illnesslbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 320, -1, -1));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel36.setText("Illness:");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 320, -1, -1));
        jPanel1.add(sexlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 220, 50, 20));

        licenselbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(licenselbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 630, -1, -1));

        txtPrecautions.setColumns(20);
        txtPrecautions.setRows(5);
        jScrollPane2.setViewportView(txtPrecautions);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 210, 80));

        txtDosandAdmin.setColumns(20);
        txtDosandAdmin.setRows(5);
        jScrollPane3.setViewportView(txtDosandAdmin);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 200, 80));

        btnAdd.setBackground(new java.awt.Color(0, 153, 153));
        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Save");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 570, 100, 30));

        btnSearch.setBackground(new java.awt.Color(0, 153, 153));
        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 80, 30));

        btnClear.setBackground(new java.awt.Color(0, 153, 153));
        btnClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 570, 90, 30));

        txtDisplay.setColumns(20);
        txtDisplay.setRows(5);
        jScrollPane1.setViewportView(txtDisplay);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 100, 530, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmboIllnessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmboIllnessActionPerformed
        // TODO add your handling code here:
        if(cmboIllness.getSelectedItem().equals("Colds"))
        {
            txtMedicine.setText("Neosep");
            txtDosage.setText("500 mg");
            txtDailyDose.setText("3x a day");
            txtDosandAdmin.setText("1 tab after meal for 7 days");
            txtStorage.setText("Store below 30°C");
            txtPrecautions.setText("Food and drugs prohibits \ndispensing without prescription.");
            txtPhysician.setText("Dr. Liza Ybañez");
        }
        else if (cmboIllness.getSelectedItem().equals("Cough"))
        {
            txtMedicine.setText("Altocetyl");
            txtDosage.setText("600 mg powder");
            txtDailyDose.setText("1 sachet once daily for 15 days ");
            txtDosandAdmin.setText("mix 1/4 glass water");
            txtStorage.setText("Store below 30°C");
            txtPrecautions.setText("Food and drugs prohibits \ndispensing without prescription");
            txtPhysician.setText("Dr. Peter Lim");
        }
        else if (cmboIllness.getSelectedItem().equals("Fever"))
        {
            txtMedicine.setText("Paracetamol");
            txtDosage.setText("500 mg");
            txtDailyDose.setText("every after 4 hours ");
            txtDosandAdmin.setText("For 3 days or until well");
            txtStorage.setText("Store below 30°C");
            txtPrecautions.setText("Avoid overdose");
            txtPhysician.setText("Dr. Peter Lim");
        }
        else if (cmboIllness.getSelectedItem().equals("Diarrhea"))
        {
            txtMedicine.setText("Azilide");
            txtDosage.setText("500 mg");
            txtDailyDose.setText("1 tab daily");
            txtDosandAdmin.setText("1 tab after lunch for 7 days ");
            txtStorage.setText("Store below 30°C");
            txtPrecautions.setText("Contains Azithromycin");
            txtPhysician.setText("Dr. Ana Bas");
        }
        if(cmboIllness.getSelectedItem().equals("HB Pressure"))
        {
            txtMedicine.setText("Lozartan");
            txtDosage.setText("500 mg");
            txtDailyDose.setText("once a day");
            txtDosandAdmin.setText("1 tab after breakfast.\n Exercise regularly ");
            txtStorage.setText("Store below 30°C");
            txtPrecautions.setText("Food and drugs prohibits \ndispensing without prescription.");
            txtPhysician.setText("Dr. Liza Ybañez");
        }
        if(cmboIllness.getSelectedItem().equals("Iron Defficiency"))
        {
            txtMedicine.setText("Montair");
            txtDosage.setText("10 mg");
            txtDailyDose.setText("1 tab a day(chewable)");
            txtDosandAdmin.setText("1 tab at bedtime\n. Drink plenty of water ");
            txtStorage.setText("Store below 30°C");
            txtPrecautions.setText("Food and drugs prohibits \ndispensing without prescription.");
            txtPhysician.setText("Dr. Janah Uy");
        }
        if(cmboIllness.getSelectedItem().equals("......"))
        {
            txtMedicine.setText("");
            txtDosage.setText("");
            txtDailyDose.setText("");
            txtDosandAdmin.setText("");
            txtStorage.setText("");
            txtPrecautions.setText("");
            txtPhysician.setText("");
            txtID.setText("");
            txtPname.setText("");
            txtAddress.setText("");
            txtAge.setText("");
            txtSex.setText("");
        }
    }//GEN-LAST:event_cmboIllnessActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String q1 = (txtMedicine.getText());
        String q2 = (txtDosage.getText());
        String q3 = (txtDailyDose.getText());
        String q4 = (txtDosandAdmin.getText());
        String q5 = (txtStorage.getText());
        String q6 = (txtPrecautions.getText());
        String q7 = (txtPhysician.getText());
        String q8 = (txtID.getText());
        String q9 = (txtPname.getText());
        String q10 = (txtAddress.getText());
        String q11 = (txtAge.getText());
        String q12 = (txtSex.getText());
        String q13 = "";
        if(cmboIllness.getSelectedItem().equals("Colds")){
            q13 = "Colds";
        }
        if(cmboIllness.getSelectedItem().equals("Cough")){
            q13 = "Cough";
        }
        if(cmboIllness.getSelectedItem().equals("Fever")){
            q13 = "Fever";
        }
        if(cmboIllness.getSelectedItem().equals("Diarrhea")){
            q13 = "Diarrhea";
        }
        if(cmboIllness.getSelectedItem().equals("HB Pressure")){
            q13 = "HB Pressure";
        }
        if(cmboIllness.getSelectedItem().equals("Iron Defficiency")){
            q13 = "Iron Defficiency";
        }

        illnesslbl.setText(q13);
        medicinelbl.setText(q1);
        dosagelbl.setText(q2);
        namelbl.setText(q9);
        addresslbl.setText(q10);
        agelbl.setText(q11);
        sexlbl.setText(q12);
        IDlbl.setText(q8);
        dailydoselbl.setText(q3);
        daAlbl.setText(q4);
        storagelbl.setText(q5);
        precautionlbl.setText(q6);
        physicianlbl.setText(q7);
        licenselbl.setText("006277");

        String illness = "";
        if(cmboIllness.getSelectedItem().equals("Colds")){
            illness = "Colds";
        }
        if(cmboIllness.getSelectedItem().equals("Cough")){
            illness = "Cough";
        }
        if(cmboIllness.getSelectedItem().equals("Fever")){
            illness = "Fever";
        }
        if(cmboIllness.getSelectedItem().equals("Diarrhea")){
            illness = "Diarrhea";
        }
        if(cmboIllness.getSelectedItem().equals("HB Pressure")){
            illness = "HB Pressure";
        }
        if(cmboIllness.getSelectedItem().equals("Iron Defficiency")){
            illness = "Iron Defficiency";
        }
        String id = txtID.getText();
        String name = txtPname.getText();
        String age = txtAge.getText();
        String sex = txtSex.getText();
        String address = txtAddress.getText();
        String medicine = txtMedicine.getText();
        String dosage = txtDosage.getText();
        String dailydose = txtDailyDose.getText();
        String dosandadmins = txtDosandAdmin.getText();
        String storage = txtStorage.getText();
        String precautions = txtPrecautions.getText();
        String physician = txtPhysician.getText();
        String d = date.getText();
        String t = time.getText();

        Prescription2 add = new Prescription2(id,name,age,sex,address,illness,medicine,dosage,dailydose,dosandadmins,storage,precautions,physician,d,t);
        if(id.isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter patient id");
        }
        else if (checkId(id)) {
            JOptionPane.showMessageDialog(null, "Patient ID already exist!\n Please try another one.");
        }
        else if(name.isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter patient name");
        }
        else if(age.isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter patient age");
        }
        else if(sex.isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter patient sex");
        }
        else if(address.isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter patient address");
        }
        else if(illness.isEmpty()){
            JOptionPane.showMessageDialog(null,"Please select patient illness");
        }
        else if(medicine.isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter medicine");
        }
        else if(dosage.isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter dosage");
        }
        else if(dailydose.isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter daily dose");
        }
        else if(dosandadmins.isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter dosae and administration");
        }
        else if(storage.isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter storage");
        }
        else if(precautions.isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter precautions");
        }
        else if(physician.isEmpty()){
            JOptionPane.showMessageDialog(null,"Please physician");
        }
        else if(add.addNew())
        JOptionPane.showMessageDialog(null,"Prescription saved!");

        txtID.setText("");
        txtPname.setText("");
        txtSex.getName();
        txtAge.setText("");
        txtAddress.setText("");
        cmboIllness.getModel().setSelectedItem("......");
        txtMedicine.setText("");
        txtDosage.setText("");
        txtPrecautions.setText("");
        txtStorage.setText("");
        txtDosandAdmin.setText("");
        txtDailyDose.setText("");
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String id = txtID.getText();
        InPatient2 reg = new InPatient2();
        ResultSet res = reg.getInfo(id);

        try{
            res.beforeFirst();
            while(res.next()){
                txtID.setText(res.getString("PatientId"));
                txtPname.setText(res.getString("FullName"));
                txtAge.setText(res.getString("Age"));
                txtSex.setText(res.getString("Gender"));
                txtAddress.setText(res.getString("Address"));
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Id does not exist!");
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtID.setText("");
        txtPname.setText("");
        txtSex.getName();
        txtAge.setText("");
        txtAddress.setText("");
        cmboIllness.getModel().setSelectedItem("......");
        txtMedicine.setText("");
        txtDosage.setText("");
        txtPrecautions.setText("");
        txtStorage.setText("");
        txtDosandAdmin.setText("");
        txtDailyDose.setText("");

        illnesslbl.setText("");
        medicinelbl.setText("");
        dosagelbl.setText("");
        namelbl.setText("");
        addresslbl.setText("");
        agelbl.setText("");
        sexlbl.setText("");
        IDlbl.setText("");
        dailydoselbl.setText("");
        daAlbl.setText("");
        storagelbl.setText("");
        precautionlbl.setText("");

    }//GEN-LAST:event_btnClearActionPerformed

    //function to check if Patient Id already exist
    public boolean checkId(String pid) {
        PreparedStatement ps;
        ResultSet rs;
        boolean checkuser = false;

        String query = "SELECT * FROM `prescription` WHERE `PatientId` =?";

        try {
            ps = MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, pid);

            rs = ps.executeQuery();

            if (rs.next()) {
                checkuser = true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Prescription2.class.getName()).log(Level.SEVERE, null, ex);
        }
        return checkuser;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientPrescriptionR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientPrescriptionR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientPrescriptionR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientPrescriptionR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientPrescriptionR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDlbl;
    private javax.swing.JLabel addresslbl;
    private javax.swing.JLabel agelbl;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox cmboIllness;
    private javax.swing.JLabel daAlbl;
    private javax.swing.JLabel dailydoselbl;
    private javax.swing.JLabel date;
    private javax.swing.JLabel dosagelbl;
    private javax.swing.JLabel illnesslbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel licenselbl;
    private javax.swing.JLabel medicinelbl;
    private javax.swing.JLabel namelbl;
    private javax.swing.JLabel physicianlbl;
    private javax.swing.JLabel precautionlbl;
    private javax.swing.JLabel sexlbl;
    private javax.swing.JLabel storagelbl;
    private javax.swing.JLabel time;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtDailyDose;
    private javax.swing.JTextArea txtDisplay;
    private javax.swing.JTextField txtDosage;
    private javax.swing.JTextArea txtDosandAdmin;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMedicine;
    private javax.swing.JTextField txtPhysician;
    private javax.swing.JTextField txtPname;
    private javax.swing.JTextArea txtPrecautions;
    private javax.swing.JTextField txtSex;
    private javax.swing.JTextField txtStorage;
    // End of variables declaration//GEN-END:variables
}
