/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Receptionist;

import PatientsInfo.AdminPortal;
import java.awt.Frame;
import java.awt.Image;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author kli ann
 */
public class Receptionist extends javax.swing.JFrame {

    /**
     * Creates new form Receptionist
     */
    public Receptionist() {
        initComponents();
        
        ImageIcon ad = new ImageIcon(getClass().getResource("receptionist.jpg")); 
        Image image = ad.getImage().getScaledInstance(110, 130, Image.SCALE_SMOOTH);
        LogoR.setIcon(new ImageIcon(image) );
        LogoUpdate.setIcon(new ImageIcon(image) );
        
        ImageIcon home = new ImageIcon(getClass().getResource("home.jpg")); 
        Image img = home.getImage().getScaledInstance(52, 57, Image.SCALE_SMOOTH);
        jLabelHome1.setIcon(new ImageIcon(img) );
        jLabelHome2.setIcon(new ImageIcon(img) );
        
        TableColumnModel tcm = tblRecords.getColumnModel();
        tcm.getColumn(0).setPreferredWidth(3);
        tcm.getColumn(1).setPreferredWidth(15);
        tcm.getColumn(2).setPreferredWidth(15);
        tcm.getColumn(3).setPreferredWidth(10);
        tcm.getColumn(4).setPreferredWidth(20);
        tcm.getColumn(5).setPreferredWidth(3);
        tcm.getColumn(6).setPreferredWidth(5);
        tcm.getColumn(7).setPreferredWidth(70);
        tcm.getColumn(8).setPreferredWidth(20);
        tcm.getColumn(9).setPreferredWidth(120);
        tcm.getColumn(10).setPreferredWidth(20);
        
        //for displaying data from table in Mysql
        DefaultTableModel model = (DefaultTableModel) tblRecords.getModel();
        model.setRowCount(0);
        
        AddReceptionist2 ar = new AddReceptionist2();
        ResultSet res = null;
        try{
            res = ar.getAll();
            res.beforeFirst();
            while(res.next()){
                model.addRow(new Object[]{Integer.parseInt(res.getString(1)),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(8),res.getString(9),res.getString(10),res.getString(11),res.getString(12),res.getString(13)});
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Cannot display" + e.toString());
        }
        
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        LogoR = new javax.swing.JLabel();
        jLabelHome1 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRecords = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        LogoUpdate = new javax.swing.JLabel();
        jLabelHome2 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtLname = new javax.swing.JTextField();
        txtBdate = new javax.swing.JTextField();
        txtSearch = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtContract = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        rdoMale = new javax.swing.JRadioButton();
        rdoFemale = new javax.swing.JRadioButton();
        cmboStatus = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel7 = new javax.swing.JPanel();
        btnDelete = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(204, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(0, 204, 204));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Receptionist/receptionist.jpg"))); // NOI18N
        jPanel11.add(LogoR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 96, 105));

        jLabelHome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Receptionist/home.jpg"))); // NOI18N
        jLabelHome1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelHome1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHome1MouseClicked(evt);
            }
        });
        jPanel11.add(jLabelHome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, 90, 60));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("All Receptionists ");
        jPanel11.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Home");
        jPanel11.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 70, -1, -1));

        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1458, 95));

        tblRecords.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RecepID", "FName", "LName", "Sex", "Bdate", "Contract", "Status", "Email", "Phone", "Address", "DRegistered"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRecords);

        jPanel10.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 1300, -1));

        btnRefresh.setBackground(new java.awt.Color(0, 153, 153));
        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel10.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 100, -1));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1480, 843));

        jTabbedPane1.addTab("Receptionists", jPanel9);

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(0, 204, 204));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Delete Receptionist");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        LogoUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Receptionist/receptionist.jpg"))); // NOI18N
        jPanel6.add(LogoUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 100, 100));

        jLabelHome2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Receptionist/home.jpg"))); // NOI18N
        jLabelHome2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelHome2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHome2MouseClicked(evt);
            }
        });
        jPanel6.add(jLabelHome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, 90, 60));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Home");
        jPanel6.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 70, -1, -1));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1460, 94));

        jLabel14.setBackground(new java.awt.Color(204, 204, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 153));
        jLabel14.setText("Address:");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 560, -1, -1));

        jLabel16.setBackground(new java.awt.Color(204, 204, 255));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 153));
        jLabel16.setText("Receptionist ID:");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, -1));

        jLabel17.setBackground(new java.awt.Color(204, 204, 255));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 153, 153));
        jLabel17.setText("Last Name:");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, -1, -1));

        jLabel18.setBackground(new java.awt.Color(204, 204, 255));
        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 153, 153));
        jLabel18.setText("Sex:");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, -1, -1));

        jLabel19.setBackground(new java.awt.Color(204, 204, 255));
        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 153, 153));
        jLabel19.setText("B-date:");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, -1, -1));

        jLabel20.setBackground(new java.awt.Color(204, 204, 255));
        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 153, 153));
        jLabel20.setText("Marital Status:");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, -1, 20));

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        jPanel5.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, 690, 40));

        txtLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLnameActionPerformed(evt);
            }
        });
        jPanel5.add(txtLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 270, 240, 40));
        jPanel5.add(txtBdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 240, 40));

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        jPanel5.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 200, 30));

        jLabel23.setBackground(new java.awt.Color(204, 204, 255));
        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 153, 153));
        jLabel23.setText("Phone:");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, -1, -1));
        jPanel5.add(txtContract, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 480, 240, 40));

        jLabel25.setBackground(new java.awt.Color(204, 204, 255));
        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 153, 153));
        jLabel25.setText("Contract No.:");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, -1, -1));
        jPanel5.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 340, 240, 40));

        rdoMale.setBackground(new java.awt.Color(51, 255, 153));
        buttonGroup1.add(rdoMale);
        rdoMale.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdoMale.setForeground(new java.awt.Color(0, 102, 102));
        rdoMale.setText("Male");
        rdoMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoMaleActionPerformed(evt);
            }
        });
        jPanel5.add(rdoMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, -1, -1));

        rdoFemale.setBackground(new java.awt.Color(51, 255, 153));
        buttonGroup1.add(rdoFemale);
        rdoFemale.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdoFemale.setForeground(new java.awt.Color(0, 102, 102));
        rdoFemale.setText("Female");
        jPanel5.add(rdoFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, -1, -1));

        cmboStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmboStatus.setForeground(new java.awt.Color(0, 153, 153));
        cmboStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Single", "Married", "Divorced", "Widow" }));
        jPanel5.add(cmboStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 240, 40));
        jPanel5.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 1450, 10));

        jPanel7.setBackground(new java.awt.Color(51, 255, 153));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 240, 50));

        btnDelete.setBackground(new java.awt.Color(0, 153, 153));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel5.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 520, 120, 30));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Receptionist/user1.jpg"))); // NOI18N
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 220, -1, -1));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), new java.awt.Color(0, 204, 204)));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 210, 210, 210));

        btnSearch.setBackground(new java.awt.Color(0, 153, 153));
        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel5.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, 110, 30));
        jPanel5.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 410, 240, 40));

        jLabel30.setBackground(new java.awt.Color(204, 204, 255));
        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 153, 153));
        jLabel30.setText("Email:");
        jPanel5.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, -1, -1));
        jPanel5.add(txtFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 240, 40));

        jLabel21.setBackground(new java.awt.Color(204, 204, 255));
        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 153, 153));
        jLabel21.setText("First Name:");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        btnClear.setBackground(new java.awt.Color(0, 153, 153));
        btnClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel5.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 520, 110, 30));

        jTabbedPane1.addTab("Delete Receptionist", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void rdoMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoMaleActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String id = txtSearch.getText();
        AddReceptionist2 ar = new AddReceptionist2();
        int p = JOptionPane.showConfirmDialog(null,"Are you sure you want to delete Receptionist?","Hospital Management System",JOptionPane.YES_NO_OPTION);
         if(p==0){
             ar.deleteRecord(id);
             JOptionPane.showMessageDialog(null, "Successfully deleted!");
         }
         
        txtSearch.setText("");
        txtFname.setText("");
        txtLname.setText("");
        buttonGroup1.clearSelection();
        txtBdate.setText("");
        cmboStatus.getModel().setSelectedItem("Select");
        txtAddress.setText("");
        txtPhone.setText("");
        txtEmail.setText("");
        txtContract.setText("");
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        
        String id = txtSearch.getText();
        AddReceptionist2 ad = new AddReceptionist2();
        ResultSet res = ad.getInfo(id);

        try {
            res.beforeFirst();
            while(res.next()){
                txtSearch.setText(res.getString("u_id"));
                txtFname.setText(res.getString("u_fname"));
                txtLname.setText(res.getString("u_lname"));
                
                String sex =res.getString("u_sex");
                if(sex.equals("Male")){
                    rdoMale.setSelected(true);
                }
                else if(sex.equals("Female")){
                    rdoFemale.setSelected(true);
                }
                
                txtBdate.setText(res.getString("u_bdate"));
                txtContract.setText(res.getString("u_contract"));
                
                String status = res.getString("u_status");
                if(status.equals("Single")){
                    cmboStatus.getModel().setSelectedItem("Single");
                }
                else if(status.equals("Married")){
                    cmboStatus.getModel().setSelectedItem("Married");
                }
                else if(status.equals("Divorced")){
                    cmboStatus.getModel().setSelectedItem("Divorced");
                }
                else if(status.equals("Widow")){
                    cmboStatus.getModel().setSelectedItem("Widow");
                }
                
                txtEmail.setText(res.getString("u_email"));
                txtPhone.setText(res.getString("u_phone"));
                txtAddress.setText(res.getString("u_address"));
                
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Id does not exist!");
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void jLabelHome2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHome2MouseClicked
        // TODO add your handling code here:
        new AdminPortal().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelHome2MouseClicked

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void jLabelHome1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHome1MouseClicked
        // TODO add your handling code here:
        AdminPortal ap = new AdminPortal();
        ap.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelHome1MouseClicked

    private void txtLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLnameActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtSearch.setText("");
        txtFname.setText("");
        txtLname.setText("");
        buttonGroup1.clearSelection();
        txtBdate.setText("");
        cmboStatus.getModel().setSelectedItem("Select");
        txtAddress.setText("");
        txtPhone.setText("");
        txtEmail.setText("");
        txtContract.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        //for refreshing data from table in Mysql
        
        DefaultTableModel model = (DefaultTableModel) tblRecords.getModel();
        model.setRowCount(0);
        
        AddReceptionist2 ar = new AddReceptionist2();
        ResultSet res = null;
        try{
            res = ar.getAll();
            res.beforeFirst();
            while(res.next()){
                model.addRow(new Object[]{Integer.parseInt(res.getString(1)),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(8),res.getString(9),res.getString(10),res.getString(11),res.getString(12),res.getString(13)});
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Cannot display" + e.toString());
        }
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receptionist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogoR;
    private javax.swing.JLabel LogoUpdate;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmboStatus;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabelHome1;
    private javax.swing.JLabel jLabelHome2;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton rdoFemale;
    private javax.swing.JRadioButton rdoMale;
    private javax.swing.JTable tblRecords;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBdate;
    private javax.swing.JTextField txtContract;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
